import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out=process.env.UI_EVIDENCE_DIR||'evidence';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROMIUM_PATH});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.text().includes('mergeGeometries')&&['error','warning'].includes(m.type()))errors.push(m.text());});
await page.goto('http://127.0.0.1:5173');
await page.waitForFunction(()=>window.__townDebug);
await page.screenshot({path:out+'/01-empty.png'});
await page.locator('#start-btn').click();
const a=await page.evaluate(()=>window.__townDebug.screenCell(-3,0));
const b=await page.evaluate(()=>window.__townDebug.screenCell(-1,0));
await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});
await page.screenshot({path:out+'/02-drag.png'});
await page.mouse.up();
let state=await page.evaluate(()=>window.__townDebug.snapshot());
assert.equal(state.blocks.length,1);assert.equal(state.buildings.length,3);
await page.locator('[data-mode="explore"]').click();
await page.mouse.click(740,420);
assert.equal((await page.evaluate(()=>window.__townDebug.snapshot())).buildings.length,3);
await page.locator('#speed-btn').click();await page.locator('#speed-btn').click();
await page.waitForFunction(()=>window.__townDebug.snapshot().people.length===6,{},{timeout:20000});
await page.locator('#pause-btn').click();
const snapshot=await page.evaluate(()=>window.__townDebug.snapshot());
const p=await page.evaluate(id=>window.__townDebug.screenBuilding(id),snapshot.buildings[0].id);
await page.mouse.click(p.x,p.y);
await page.waitForFunction(()=>!document.querySelector('#inspector').hidden);
await page.screenshot({path:out+'/03-inhabited.png'});
await page.locator('#help-btn').click();await page.locator('#new-town').click();await page.locator('#confirm-new').click();await page.locator('#demo-btn').click();
await page.locator('#pause-btn').click();
await page.waitForFunction(()=>window.__townDebug.snapshot().people.some(p=>p.outside));
await page.screenshot({path:out+'/04-demo-day.png'});
await page.locator('#light-toggle').click();
await page.waitForFunction(()=>document.body.classList.contains('night'));
await page.waitForFunction(()=>window.__townDebug.snapshot().people.every(p=>p.current===p.home),{},{timeout:25000});
await page.screenshot({path:out+'/05-demo-night.png'});
await page.locator('#concepts-btn').click();
const images=await page.locator('#gallery img').evaluateAll(imgs=>imgs.map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0})));
await page.locator('[data-close="gallery"]').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:out+'/06-mobile.png'});
const fits=await page.locator('.toolbar').evaluate(e=>e.getBoundingClientRect().right<=innerWidth&&e.getBoundingClientRect().left>=0);
assert(fits);assert.equal(errors.length,0,errors.join('\n'));
const info=await page.evaluate(()=>window.__townDebug.renderInfo());
await writeFile(out+'/browser-check.json',JSON.stringify({passed:true,errors,images,drawCalls:info.calls,triangles:info.triangles,checks:['three-cell drag','explore does not build','construction and population','building inspection','reset confirmation','demo resident movement','night switch','mobile toolbar']},null,2));
console.log(JSON.stringify({passed:true,errors,images,render:info}));
await browser.close();
