import {test} from 'node:test';import assert from 'node:assert/strict';
import {Town} from '../src/simulation.js';import {assignJobs,commuteDistance,JOB_GRACE_SECONDS} from '../src/employment.js';import {transfer,tickProduction} from '../src/production.js';
function townWithJobs(){const t=new Town();t.place('home',[{x:0,z:0}],true);t.place('work',[{x:-6,z:0}],true);t.place('work',[{x:1,z:0}],true);t.tick(.05);for(const p of t.people)p.work=null;return t;}
test('nearest reachable job wins over earlier building order; reasonable existing job remains',()=>{const t=townWithJobs(),p=t.people[0],far=t.buildings[1],near=t.buildings[2];assert(commuteDistance(t,p,near)<commuteDistance(t,p,far));assignJobs(t);assert.equal(p.work,near.id);p.work=far.id;assignJobs(t);assert.equal(p.work,far.id);});
test('isolated vacancies remain empty; reconnecting fills jobs; lost work receives a grace period',()=>{
 const t=townWithJobs(),p=t.people[0],roads=t.roads;t.roads=new Set([t.buildings[0].entrance.join(',')]);assignJobs(t);assert.equal(p.work,null);
 t.roads=roads;assignJobs(t);const job=p.work;assert(job);t.roads=new Set([t.buildings[0].entrance.join(',')]);assignJobs(t);assert.equal(p.work,job);assert.doesNotThrow(()=>Town.restore(t.toJSON()));t.elapsed+=JOB_GRACE_SECONDS-1;assignJobs(t);assert.equal(p.work,job);t.elapsed+=1;assignJobs(t);assert.equal(p.work,null);t.roads=roads;assignJobs(t);assert(p.work);assert.doesNotThrow(()=>Town.restore(t.toJSON()));
});
function production(workers){const t=new Town();t.place('work',[{x:0,z:0}],true);const b=t.buildings[0];b.variant=0;t.workers=()=>Array.from({length:workers},()=>({outside:false,current:b.id}));transfer(t,'boat',`input:${b.id}`,3,'clay');for(let i=0;i<1200;i++)tickProduction(t,.05);return {count:t.economy.lots.filter(l=>l.good==='ceramics').length,input:t.economy.lots.filter(l=>l.at===`input:${b.id}`).length,progress:t.economy.lots.map(l=>l.progress||0)};}
test('four present craftspeople produce more than one; no workers consume no inputs',()=>{const none=production(0),one=production(1),four=production(4);assert(four.count>one.count);assert.equal(none.count,0);assert.equal(none.input,3);assert(none.progress.every(n=>n===0));});
