import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,writeFile,readFile} from 'node:fs/promises';
const out=process.env.LEARNING_EVIDENCE||'evidence/learning/student';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.TEST_CHROMIUM_PATH});
const page=await browser.newPage({viewport:{width:1360,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
page.setDefaultTimeout(15000);
try{
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5192');await expect(page.locator('#stage-select')).toBeVisible();await expect(page.locator('.stage-kaifeng')).toContainText('我能分辨');await page.locator('[data-stage-enter="kaifeng"]').click();
await expect(page.locator('.learning-next')).toContainText('第 1 段');await page.locator('[data-learning-level]').selectOption('story');await page.locator('[data-learning-zhuyin]').check();await expect(page.locator('.learning-support ruby')).toHaveCount(3);await expect(page.locator('.learning-story')).toBeVisible();await expect(page.locator('.learning-story-diagram svg')).toBeVisible();
await page.locator('[data-learning="answer"]').click();await expect(page.locator('#literary-status')).toContainText('先選答案');
await page.locator('[data-learning-field="answer"][value="0"]').check();await page.locator('[data-learning-field="evidence"]').selectOption('0');await page.locator('[data-learning-field="reason"]').fill('官位高所以我先相信。');await page.locator('[data-learning="answer"]').click();await expect(page.locator('#literary-status')).toContainText('這次想法已保留');
await page.locator('[data-learning="hint"]').click();await expect(page.locator('.learning-reading')).toContainText('提示一');await expect(page.locator('[data-learning-field="reason"]')).toHaveValue('官位高所以我先相信。');
await page.locator('[data-learning-field="answer"][value="1"]').check();await page.locator('[data-learning-field="reason"]').fill('街坊說只聽人說，所以先查證。');await page.locator('[data-learning="answer"]').click();await expect(page.locator('.learning-next')).toContainText('第 2 段');
await page.locator('.learning-portfolio summary').click();await page.locator('[data-learning-field="revisionText"]').fill('包公很公平。');await page.locator('[data-learning="revision"]').click();await page.locator('.learning-portfolio summary').click();await page.locator('[data-learning-field="revisionText"]').fill('包公要求查證，不依官位判定。');await page.locator('[data-learning-field="feedback"]').fill('補上具體做法');await page.locator('[data-learning-field="changes"]').fill('加上查證與官位的對照');await page.locator('[data-learning="revision"]').click();await expect(page.locator('.learning-portfolio summary')).toContainText('2 版');
await page.locator('.learning-transfer summary').click();await page.locator('[data-learning-field="transferAnswer"][value="0"]').check();await page.locator('[data-learning-field="transferReason"]').fill('先聽雙方，找可查證的線索。');await page.locator('[data-learning="transfer"]').click();await expect(page.locator('.learning-transfer')).toContainText('選擇符合');
await page.locator('.learning-portfolio summary').click();const cardDownload=page.waitForEvent('download');await page.locator('[data-learning=card]').click();await(await cardDownload).saveAs(out+'/work-card.svg');const card=await readFile(out+'/work-card.svg','utf8');assert(card.includes('包公要求查證'));assert(card.includes('xmlns="http://www.w3.org/2000/svg"'));
await page.locator('.learning-transfer summary').click();await page.locator('[data-learning-field=reviewKind]').selectOption('recall');await page.locator('.learning-transfer summary').click();await page.locator('[data-learning-field=variant]').selectOption('0');await page.locator('.learning-transfer summary').click();await page.locator('[data-learning-field=transferAnswer][value="1"]').check();await page.locator('[data-learning-field=transferReason]').fill('街坊說只聽人說');await page.locator('[data-learning=transfer]').click();await expect(page.locator('.learning-transfer')).toContainText('上次原文回憶');
await page.reload();await expect(page.locator('#stage-select')).toBeVisible();await page.locator('[data-stage-enter="kaifeng"]').click();await expect(page.locator('.learning-next')).toContainText('第 2 段');await expect(page.locator('[data-learning-level]')).toHaveValue('story');await expect(page.locator('.learning-portfolio summary')).toContainText('2 版');
await page.screenshot({path:out+'/desktop.png'});await page.setViewportSize({width:390,height:844});assert(await page.locator('#literary-quests').evaluate(d=>d.scrollWidth<=d.clientWidth));await page.screenshot({path:out+'/mobile.png'});
assert.deepEqual(errors,[]);await writeFile(out+'/result.json',JSON.stringify({readingSupport:true,zhuyin:true,wrongAnswerRetained:true,hintPreservesDraft:true,evidenceAndReasonProgression:true,revisions:2,transfer:true,originalRecall:true,storyDiagram:true,workCardDownload:true,reload:true,mobileWidth:390,errors},null,2));console.log('student learning browser passed');
}finally{await browser.close();}
