import test from 'node:test';import assert from 'node:assert/strict';
import {Town} from '../src/simulation.js';import {validateSave} from '../src/save-schema.js';import {commitJourney} from '../src/journey.js';
import {LITERARY_QUESTS} from '../src/literary-quests.js';import {LEARNING_CONTENT} from '../src/learning-content.js';
import {DAY,evidenceLines,learningState,learningQuest,setReadingSupport,useLearningHint,recordLearningAnswer,saveLearningRevision,recordPrediction,recordTransfer,reviewDue,learningSummary,validateLearning} from '../src/learning.js';
const response=(id,step=0)=>({step,answer:LITERARY_QUESTS[id].steps[step].answer,evidence:evidenceLines(id).findIndex(x=>x.step===step),reason:'我的理由引用了這段文字。',at:1000});
test('all ten learning packs have distinct goals, three supports and two transfer situations',()=>{assert.deepEqual(Object.keys(LEARNING_CONTENT).sort(),Object.keys(LITERARY_QUESTS).sort());assert.equal(new Set(Object.values(LEARNING_CONTENT).map(c=>c.goal)).size,10);for(const c of Object.values(LEARNING_CONTENT)){assert.equal(c.plain.length,3);assert.equal(c.words.length,3);assert.equal(c.transfer.length,2);assert(c.story.length>10);for(const q of c.transfer)assert(q.choices[q.answer]);}});
test('learning attempts preserve wrong choices and hints; progression needs relevant excerpt; reasons remain ungraded',()=>{const t=new Town();assert(useLearningHint(t,'kaifeng',0));let a=response('kaifeng');assert(recordLearningAnswer(t,'kaifeng',{...a,answer:0}));assert.equal(t.journey.literary?.kaifeng,undefined);assert(recordLearningAnswer(t,'kaifeng',{...a,evidence:evidenceLines('kaifeng').findIndex(x=>x.step===1)}));assert.equal(t.journey.literary?.kaifeng,undefined);assert(recordLearningAnswer(t,'kaifeng',a));assert.equal(t.journey.literary.kaifeng.step,1);assert.equal(learningQuest(t,'kaifeng').attempts.length,3);assert.equal(learningSummary(t,'kaifeng').independentEvidence,0);assert(learningSummary(t,'kaifeng').needsReview);assert.equal(recordLearningAnswer(t,'kaifeng',a),false);validateSave(t.toJSON());assert.deepEqual(Town.restore(t.toJSON()).journey.learning,t.journey.learning);});
test('learning transactions preserve town on storage failure and old cities need no migration',()=>{const t=new Town(),before=t.toJSON();assert.equal(commitJourney(t,x=>recordLearningAnswer(x,'kaifeng',response('kaifeng')),()=>({ok:false})),false);assert.deepEqual(t.toJSON(),before);validateSave(Town.restore(before).toJSON());assert(setReadingSupport(t,'story',true));assert.equal(learningState(t).level,'story');assert.equal(setReadingSupport(t,'not-a-level',false),false);validateSave(t.toJSON());});
test('revision history retains initial explanation and requires feedback plus change explanation',()=>{const t=new Town();assert(saveLearningRevision(t,'kaifeng',{text:'包公很公平',at:1}));assert.equal(saveLearningRevision(t,'kaifeng',{text:'包公查證',at:2}),false);assert(saveLearningRevision(t,'kaifeng',{text:'包公仍查證婚姻關係',feedback:'指出具體行動',changes:'補上查證行動',at:3}));assert.equal(learningQuest(t,'kaifeng').revisions[0].text,'包公很公平');validateSave(t.toJSON());});
test('review uses real elapsed days and records transfer answer separately from reasoning quality',()=>{const t=new Town();recordLearningAnswer(t,'kaifeng',response('kaifeng'));t.elapsed+=DAY;assert.equal(reviewDue(t,'kaifeng',1001),false);assert(reviewDue(t,'kaifeng',1000+DAY));assert(recordTransfer(t,'kaifeng',{variant:0,answer:0,reason:'先聽雙方，再找證據',at:1000+DAY}));assert(learningQuest(t,'kaifeng').reviews[0].delayed);assert.equal(reviewDue(t,'kaifeng',1001+DAY),false);assert(learningSummary(t,'kaifeng').transferReasonNeedsReview);validateLearning(t.journey.learning);});
test('prediction cannot be rewritten after observing outcome',()=>{const t=new Town();assert(recordPrediction(t,'yueyang',{choice:'tower',reason:'先讓城市好看',at:1}));assert(recordPrediction(t,'yueyang',{choice:'care',reason:'改主意',observation:'居民仍需要住處',at:2}));assert.equal(learningQuest(t,'yueyang').prediction.choice,'tower');validateSave(t.toJSON());});
test('save validation rejects unknown fields, forged correctness, invalid evidence and oversized records',()=>{const t=new Town();recordLearningAnswer(t,'kaifeng',response('kaifeng'));for(const mutate of [s=>s.secret='x',s=>s.quests.kaifeng.attempts[0].correct=false,s=>s.quests.kaifeng.attempts[0].evidence=999,s=>s.quests.kaifeng.attempts[0].reason='字'.repeat(401),s=>s.quests.kaifeng.attempts=Array(91).fill(s.quests.kaifeng.attempts[0])]){const copy=structuredClone(t.toJSON());mutate(copy.journey.learning);assert.throws(()=>validateSave(copy));}});

test('recall and transfer remain separate, delayed flags cannot pretend immediate work was spaced',()=>{const t=new Town();recordLearningAnswer(t,'kaifeng',response('kaifeng'));assert(recordTransfer(t,'kaifeng',{kind:'recall',variant:0,answer:1,reason:'來源是聽別人說',at:1001}));assert.equal(learningQuest(t,'kaifeng').reviews[0].kind,'recall');assert.equal(learningQuest(t,'kaifeng').reviews[0].correct,true);const d=structuredClone(t.toJSON());d.journey.learning.quests.kaifeng.reviews[0].delayed=true;assert.throws(()=>validateSave(d));assert(saveLearningRevision(t,'kaifeng',{text:'時鐘回撥仍可保留',at:1}));assert.equal(learningQuest(t,'kaifeng').revisions[0].at,1001);validateSave(t.toJSON());});
