import {test} from 'node:test';import assert from 'node:assert/strict';
import {SaveStore} from '../src/save-store.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),key:i=>[...m.keys()][i],get length(){return m.size;}};};
const validate=d=>{if(!d||!Number.isInteger(d.value))throw Error('測試資料無效');return structuredClone(d);};
const make=(storage,owner='a')=>new SaveStore({storage,owner,validate,now:()=>123});
test('bad primary is quarantined and never overwritten by autosave',()=>{const s=memory();s.setItem('bianshui-town-v1','{bad');const a=make(s);assert.equal(a.load().status,'recovery');assert.equal(a.save({value:3}).ok,false);assert.equal(s.getItem(a.key),'{bad');assert.equal(a.rescueRaw(),'{bad');});
test('only valid prior data becomes backup and reset snapshot survives reload and autosaves',()=>{const s=memory(),a=make(s);a.load();assert(a.save({value:1}).ok);assert(a.save({value:2}).ok);assert.equal(a.candidate('backup').value,1);assert(a.checkpoint({value:2}).ok);assert(a.replace({value:0}).ok);a.save({value:3});a.save({value:4});const b=make(s);b.load();assert.equal(b.candidate('reset').value,2);s.setItem(a.key,'bad');const c=make(s);assert.equal(c.load().status,'recovery');assert.equal(c.candidate('backup').value,3);});
test('stale tabs cannot overwrite and each tab retains an exportable local branch',()=>{const s=memory(),a=make(s,'a'),b=make(s,'b');a.load();b.load();assert(a.save({value:1}).ok);assert.equal(b.save({value:2}).status,'conflict');assert.equal(make(s).load().data.value,1);assert.equal(b.candidate('branch:b').value,2);assert.equal(a.candidate('branch:a').value,1);assert(b.replace({value:2}).ok);assert.equal(a.save({value:3}).status,'conflict');assert.equal(make(s).load().data.value,2);});
test('import preview validates before replace; invalid input and unavailable storage preserve current data',()=>{const s=memory(),a=make(s);a.load();a.save({value:7});assert.throws(()=>a.preview('{bad'));assert.throws(()=>a.preview('{"value":"wrong"}'));assert.equal(a.load().data.value,7);assert.equal(a.preview(a.export({value:8})).value,8);s.setItem=()=>{throw Error('quota')};assert.equal(a.save({value:9}).status,'storage-error');assert.equal(s.getItem(a.key).includes('7'),true);});
