import {LITERARY_QUESTS} from '../src/literary-quests.js';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {Town} from '../src/simulation.js';import {DESIGNS,squareCells} from '../src/heritage.js';import {upgradeBuilding,moveBuilding} from '../src/urban.js';import {tierOf} from '../src/building-tiers.js';import {TownScene} from '../src/scene.js';import {createHash} from 'node:crypto';import * as THREE from 'three';import {MAX_RANK} from '../src/milestones.js';
const ranked=(o)=>{const t=new Town(o);t.city.rank=MAX_RANK;t.journey.literary=Object.fromEntries(Object.keys(LITERARY_QUESTS).map(id=>[id,{step:4,note:''}]));return t;};
test('every catalog design and available footprint progresses through five distinct models, never six',()=>{
 for(const [id,d] of Object.entries(DESIGNS))for(const size of d.sizes){const t=ranked();assert(t.place(d.type,size===4?squareCells({x:0,z:0}):[{x:0,z:0}],true,id));const b=t.buildings[0],design=b.design,plots=JSON.stringify(b.footprint),hashes=new Set();let previous=0;
 for(let tier=1;tier<=5;tier++){assert.equal(tierOf(b),tier);const m=TownScene.prototype.buildHouse.call({},b),h=createHash('sha256');let count=0;m.traverse(o=>{if(o.geometry?.attributes.position){const a=o.geometry.attributes.position.array;assert([...a].every(Number.isFinite));count+=a.length;h.update(Buffer.from(a.buffer));}});const bounds=new THREE.Box3().setFromObject(m);assert(Number.isFinite(bounds.max.y)&&bounds.max.y>0);if(tier>1){assert.equal(m.userData.upgradeFeatures.length,tier-1);assert.equal(new Set(m.userData.upgradeFeatures).size,tier-1);}hashes.add(h.digest('hex'));assert(count>previous,`${id} tier ${tier} adds geometry`);previous=count;assert.equal(b.design,design);assert.equal(JSON.stringify(b.footprint),plots);if(tier<5)assert(upgradeBuilding(t,b.id));}assert.equal(hashes.size,5);const before=JSON.stringify(t);assert(!upgradeBuilding(t,b.id));assert.equal(JSON.stringify(t),before);
 }
});
test('five tiers survive serialization, moving and four-cell expansion without losing residents or inventory',()=>{const t=new Town();t.place('home',[{x:-4,z:0}],true,'bambooHome');t.tick(.1);const b=t.buildings[0],people=t.people.map(p=>p.id);for(let i=0;i<4;i++)assert(upgradeBuilding(t,b.id));assert(upgradeBuilding(t,b.id,true));assert.equal(tierOf(b),5);assert.equal(b.design,'bambooHome');assert(moveBuilding(t,b.id,{x:0,z:0}));const r=Town.restore(JSON.parse(JSON.stringify(t)));assert.equal(tierOf(r.building(b.id)),5);assert.deepEqual(r.people.map(p=>p.id),people);assert.deepEqual(r.economy,t.economy);});
test('old saves start at visual tier one with existing functional upgrades intact; incomplete construction cannot upgrade',()=>{const t=new Town();t.place('work',[{x:0,z:0}],true,'dyeHouse');const data=JSON.parse(JSON.stringify(t));delete data.buildings[0].tier;const r=Town.restore(data);assert.equal(tierOf(r.buildings[0]),1);assert.equal(r.buildings[0].level,2);for(const value of [-4,99,1.5,null]){data.buildings[0].tier=value;assert.throws(()=>Town.restore(data),/tier/);}const a=new Town();a.place('garden',[{x:0,z:0}],false,'pond');assert(!upgradeBuilding(a,a.buildings[0].id));});
