import {test} from 'node:test';import assert from 'node:assert/strict';
import {Town,pathfind,key} from '../src/simulation.js';import {layRoad,removeRoad,moveBuilding,demolishBuilding,upgradeBuilding} from '../src/urban.js';import {goodsBalance,transfer} from '../src/production.js';
const run=(t,n)=>{for(let i=0;i<n*20;i++)t.tick(.05);};
test('public streets connect to doors, block construction, persist and can be removed',()=>{const t=new Town();t.place('home',[{x:0,z:0}],true);assert(layRoad(t,'lane',[{x:0,z:1},{x:1,z:1}]));assert(pathfind(t.roads,key(0,2),key(4,4)).length);assert(!t.place('home',[{x:0,z:1}]));assert(!layRoad(t,'avenue',[{x:0,z:0}]));assert(layRoad(t,'avenue',[{x:0,z:1}]));assert.equal(t.publicWorks.length,2);const r=Town.restore(JSON.parse(JSON.stringify(t)));assert.deepEqual(r.publicWorks,t.publicWorks);assert(removeRoad(r,[{x:0,z:1},{x:1,z:1}]));assert.equal(r.publicWorks.length,0);});
test('moving one connected house preserves occupants and leaves its neighbour intact',()=>{const t=new Town();t.place('home',[{x:0,z:0},{x:1,z:0}],true);run(t,1);const [b,other]=t.buildings,ids=t.residents(b).map(p=>p.id);assert(moveBuilding(t,b.id,{x:-4,z:2}));assert.equal(t.building(other.id).x,1);assert.deepEqual(t.residents(b).map(p=>p.id),ids);assert.equal(b.x,-4);const before=JSON.stringify(t);assert(!moveBuilding(t,b.id,{x:1,z:0}));assert.equal(JSON.stringify(t),before);run(t,50);assert(t.people.every(p=>Number.isFinite(p.x)));});
test('demolition conserves cargo, residents survive and are rehoused without dangling references',()=>{const t=new Town();t.demo();run(t,50);const home=t.buildings.find(b=>b.type==='home'),residentIds=t.residents(home).map(p=>p.id),work=t.buildings.find(b=>b.type==='work');transfer(t,'boat',`input:${work.id}`,2);const count=t.economy.lots.length;assert(demolishBuilding(t,work.id));assert.equal(t.economy.lots.length,count);assert(!t.economy.lots.some(l=>l.at===`input:${work.id}`));assert(demolishBuilding(t,home.id));assert(residentIds.every(id=>t.people.some(p=>p.id===id)));run(t,20);assert(t.people.every(p=>!p.home||t.building(p.home)));for(const b of [...t.buildings])demolishBuilding(t,b.id);run(t,3);t.place('home',[{x:-4,z:0}],true);run(t,2);assert.equal(t.residents(t.buildings[0]).length,2);assert.deepEqual(goodsBalance(t),{imported:t.economy.imported,accounted:t.economy.imported});});
test('home and workshop upgrades expand capacity, preserve variants and reject occupied four-grid expansion',()=>{const t=new Town();t.place('home',[{x:0,z:0}],true);t.place('work',[{x:-4,z:0}],true);run(t,1);const h=t.buildings[0],w=t.buildings[1],variant=w.variant;assert(upgradeBuilding(t,h.id));run(t,1);assert.equal(t.residents(h).length,4);assert(upgradeBuilding(t,h.id,true));run(t,1);assert.equal(t.residents(h).length,8);assert.equal(h.footprint.length,4);assert(upgradeBuilding(t,w.id,true));assert.equal(w.variant,variant);assert.equal(w.level,2);assert(!upgradeBuilding(t,w.id,true));const r=Town.restore(JSON.parse(JSON.stringify(t)));assert.equal(r.toJSON().version,9);assert.equal(r.building(h.id).footprint.length,4);});
test('editing roads while a loaded cart is moving never delivers to a missing shop',()=>{const t=new Town();t.demo();run(t,60);const cart=t.carts[0];assert(cart);transfer(t,'boat',`cart:${cart.id}`,1);cart.outside=true;cart.current=null;assert(layRoad(t,'avenue',[{x:-7,z:0}]));run(t,120);assert(!t.economy.lots.some(l=>l.at==='shop:null'||l.at==='shop:undefined'));assert.equal(goodsBalance(t).imported,goodsBalance(t).accounted);});
test('visitors actually walk onto a connected public street',()=>{const t=new Town();t.place('home',[{x:0,z:0}],true);t.place('shop',[{x:1,z:0}],true);assert(layRoad(t,'lane',[{x:0,z:1},{x:1,z:1}]));let used=false;for(let i=0;i<6000;i++){t.tick(.05);if(t.life.visitors.some(a=>a.visible&&Math.abs(a.z-4)<.2&&(Math.abs(a.x)<.2||Math.abs(a.x-4)<.2)))used=true;}assert(used);});
