import {test} from 'node:test';import assert from 'node:assert/strict';import {Town,dragCells,key,pathfind} from '../src/simulation.js';import {squareCells,DESIGNS} from '../src/heritage.js';import {NEW_DESIGNS} from '../src/variety.js';import {layRoad,publicSquares,removeRoad} from '../src/urban.js';import {marketStalls} from '../src/market.js';import {TownScene} from '../src/scene.js';import {createHash} from 'node:crypto';
const run=(t,n)=>{for(let i=0;i<n*20;i++)t.tick(.05);};
test('dragging diagonally in any direction forms a square; straight dragging allows four houses',()=>{for(const [x,z] of [[1,1],[-1,1],[1,-1],[-1,-1]]){const t=new Town(),cells=dragCells({x:0,z:0},{x,z});assert.equal(cells.length,4);const block=t.place('home',cells,true);assert(block.combined);assert.equal(t.buildings.length,1);assert.equal(t.buildings[0].design,'mansion');}const t=new Town();const block=t.place('home',dragCells({x:-5,z:0},{x:1,z:0}),true);assert(!block.combined);assert.equal(t.buildings.length,4);});
test('ten styles have distinct geometry and each four-grid layout differs from its small house',()=>{assert.equal(Object.keys(NEW_DESIGNS).length,10);const hashes=new Set();for(const [id,d] of Object.entries(NEW_DESIGNS)){const pair=[];for(const large of [false,true]){const t=new Town();assert(t.place(d.type,large?squareCells({x:0,z:0}):[{x:0,z:0}],true,id));const b=t.buildings[0],m=TownScene.prototype.buildHouse.call({},b),h=createHash('sha256');m.traverse(o=>{if(o.geometry?.attributes.position){const a=o.geometry.attributes.position.array;assert([...a].every(Number.isFinite));h.update(Buffer.from(a.buffer));}});pair.push(h.digest('hex'));assert.equal(b.name,large?d.largeName:d.name);}assert.notEqual(pair[0],pair[1]);hashes.add(pair[0]);}assert.equal(hashes.size,10);});
test('four road plots automatically form a traversable plaza and split on removal',()=>{const t=new Town();t.place('home',[{x:-3,z:0}],true);for(const c of squareCells({x:0,z:0}))assert(layRoad(t,'lane',[c]));assert.equal(publicSquares(t).length,1);assert(pathfind(t.roads,key(0,0),key(5,5)).length);assert(t.roads.has(key(3,3)));removeRoad(t,[{x:1,z:1}]);assert.equal(publicSquares(t).length,0);assert(!t.roads.has(key(3,3)));});
test('four separately placed flower gardens become one special landscape with valid resident references',()=>{const t=new Town();t.place('home',[{x:-4,z:0}],true);t.tick(.1);const p=t.people[0];const cells=squareCells({x:0,z:0});for(const [i,c] of cells.entries()){const block=t.place('garden',[c],true,'garden');assert(block);if(i===1){p.current=t.buildings.find(b=>b.blockId===block.id).id;p.destination=p.current;}}const garden=t.buildings.find(b=>b.design==='scholarGarden');assert(garden);assert.equal(t.buildings.filter(b=>b.type==='garden').length,1);assert.equal(garden.footprint.length,4);assert.equal(p.current,garden.id);assert.equal(p.destination,garden.id);run(t,20);assert(t.people.every(p=>!p.current||t.building(p.current)));});
test('stalls receive visitors, market counts survive reload and storytelling uses the wazi',()=>{const t=new Town();t.place('home',squareCells({x:-5,z:0}),true,'mansion');t.place('garden',[{x:-2,z:0}],true,'wazi');t.place('shop',[{x:0,z:0}],true,'bookshop');t.time=9;assert.equal(marketStalls(t).length,4);let heard=false;for(let i=0;i<6000;i++){t.tick(.05);if(t.stories.active?.type==='story'&&t.stories.active.venue==='街巷說書棚')heard=true;}assert(heard);assert(t.market.trades>0);const r=Town.restore(JSON.parse(JSON.stringify(t)));assert.equal(r.market.trades,t.market.trades);assert.equal(r.toJSON().version,9);});
import {upgradeBuilding} from '../src/urban.js';
test('expanding a new style preserves its identity and upgrades its name',()=>{const t=new Town();t.place('work',[{x:0,z:0}],true,'dyeHouse');const b=t.buildings[0];assert(upgradeBuilding(t,b.id,true));assert.equal(b.design,'dyeHouse');assert.equal(b.name,'彩帛大院');assert.equal(b.variant,2);});
