import {chromium} from '@playwright/test';
const [,,out,...steps]=process.argv;
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:1280,height:720}});
const errs=[];p.on('pageerror',e=>errs.push(String(e)));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto('http://127.0.0.1:4173/?storage-test=1',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
await p.screenshot({path:`${out}/01-initial.png`});
const box=async sel=>{const e=await p.$(sel);if(!e)return null;const r=await e.boundingBox();return r&&{w:Math.round(r.width),h:Math.round(r.height)};};
const info={initial:{treasury:await box('#hud-treasury'),demand:await box('#hud-demand'),nextStep:await box('#next-step'),treasuryText:await p.textContent('#hud-treasury').catch(()=>null)}};
await p.click('#start-btn');await p.waitForTimeout(1200);
await p.screenshot({path:`${out}/02-after-start.png`});
info.afterStart={treasury:await box('#hud-treasury'),nextStep:await p.textContent('#next-step-text').catch(()=>null),treasuryText:await p.textContent('#hud-treasury').catch(()=>null)};
// place a home
await p.click('[data-mode="home"]');await p.waitForTimeout(400);
const c=await p.$('#world');const r=await c.boundingBox();
await p.mouse.click(r.x+r.width*0.45,r.y+r.height*0.55);await p.waitForTimeout(1500);
await p.screenshot({path:`${out}/03-after-build.png`});
info.afterBuild={treasuryText:await p.textContent('#hud-treasury').catch(()=>null),nextStep:await p.textContent('#next-step-text').catch(()=>null),demandScores:await p.$$eval('.demand-score',e=>e.map(x=>x.textContent))};
await p.waitForTimeout(6000);
await p.screenshot({path:`${out}/04-later.png`});
info.later={treasuryText:await p.textContent('#hud-treasury').catch(()=>null),nextStep:await p.textContent('#next-step-text').catch(()=>null)};
const m=await b.newPage({viewport:{width:390,height:844}});
await m.goto('http://127.0.0.1:4173/?storage-test=1',{waitUntil:'networkidle'});await m.waitForTimeout(2500);
await m.screenshot({path:`${out}/05-mobile.png`});
info.mobile={treasury:await (async()=>{const e=await m.$('#hud-treasury');const bb=e&&await e.boundingBox();return bb&&{w:Math.round(bb.width),h:Math.round(bb.height)};})()};
info.errors=errs;
console.log(JSON.stringify(info,null,1));
await b.close();
