import {storyDiagram,workCardSVG} from './learning-scenes.js';
import {recallTask} from './learning-recall.js';
import {readStoredFeedback} from './learning-reports.js';
import {escapeHTML as esc} from './content-html.js';
import {LITERARY_QUESTS} from './literary-quests.js';
import {LEARNING_CONTENT,READING_LEVELS} from './learning-content.js';
import {learningState,learningQuest,evidenceLines,setReadingSupport,useLearningHint,recordLearningAnswer,saveLearningRevision,recordTransfer,reviewDue,recordPrediction} from './learning.js';
const field=(id,name)=>`data-learning-field="${name}" data-learning-quest="${id}"`;
export function createLearningUI({getTown,change,rerender}){
 let drafts={},identity=getTown();
 const draft=id=>{if(identity!==getTown()){identity=getTown();drafts={};}return drafts[id]??={};};
 const say=message=>rerender(message);
 function reading(id,step){
  const c=LEARNING_CONTENT[id],profile=learningState(getTown()),q=LITERARY_QUESTS[id],s=q.steps[step],state=learningQuest(getTown(),id),d=draft(id);
  const support=`<section class="learning-support"><strong>玩完我能：${esc(c.goal)}</strong><label>閱讀支援（隨時可切換）<select data-learning-level data-learning-quest="${id}">${Object.entries(READING_LEVELS).map(([v,label])=>`<option value="${v}" ${v===profile.level?'selected':''}>${label}</option>`).join('')}</select></label><label><input type="checkbox" data-learning-zhuyin ${profile.zhuyin?'checked':''}>顯示語詞注音</label><details ${profile.level==='story'?'open':''}><summary>故事與語詞小幫手</summary>${profile.level==='story'?storyDiagram(id):''}<p class="learning-story"><span aria-hidden="true">${c.icon}</span> ${esc(c.story)}</p><dl>${c.words.map(([w,z,meaning])=>`<dt>${profile.zhuyin?`<ruby>${esc(w)}<rt>${esc(z)}</rt></ruby>`:esc(w)}</dt><dd>${esc(meaning)}</dd>`).join('')}</dl><p>注音提供重點語詞；故事為教學改寫，原文與來源保留在下方。低年級可和老師一起讀。</p></details></section>`;
  if(!s)return support;
  const hints=state.hints[step],attempts=state.attempts.filter(a=>a.step===step),last=attempts.at(-1);
  return `${support}<section class="learning-reading"><p class="learning-next">現在只做這一步：讀第 ${step+1} 段 → 選答案與證據 → 說明理由。</p><h4>${esc(s.title)}</h4><details class="learning-context"><summary>前後段落一起讀</summary><p>本關依文章順序選讀三段，保留前後脈絡；完整作品可開啟上方來源。</p>${q.steps.map(part=>`<h5>${esc(part.title)}</h5><blockquote>${esc(part.text)}</blockquote>`).join('')}</details>${profile.level!=='independent'?`<p class="learning-plain">白話引導：${esc(c.plain[step])}</p>`:'<details><summary>需要白話引導</summary><p>'+esc(c.plain[step])+'</p></details>'}<div class="learning-lines">${s.text.split('\n').map((line,i)=>`<div><blockquote>${esc(line)}</blockquote><button data-learning="speak" data-quest-id="${id}" data-step="${step}" data-line="${i}">朗讀第 ${i+1} 句</button></div>`).join('')}</div><button data-learning="stop-speech">停止朗讀</button><p>${esc(s.prompt)}</p><fieldset><legend>我的選擇</legend>${s.choices.map((choice,i)=>`<label><input type="radio" name="learning-answer" value="${i}" ${field(id,'answer')} ${d.answer===String(i)?'checked':''}>${esc(choice)}</label>`).join('')}</fieldset><label>哪一句能支持我的選擇？<select ${field(id,'evidence')}><option value="">請選原文或改編證詞</option>${evidenceLines(id).map((line,i)=>`<option value="${i}" ${d.evidence===String(i)?'selected':''}>${esc(line.text)}</option>`).join('')}</select></label><label>我的理由（也可以先和老師口述，再一起記下）<textarea maxlength="400" rows="2" ${field(id,'reason')} placeholder="我選這樣做，因為文中……">${esc(d.reason||'')}</textarea></label><button data-learning="answer" data-quest-id="${id}" data-step="${step}">記錄選擇與理由</button><button data-learning="hint" data-quest-id="${id}" data-step="${step}" ${hints>=3?'disabled':''}>${hints>=3?'三層提示已展開':`需要線索（${hints}/3）`}</button>${hints>=1?`<p>提示一：${esc(s.hint)}</p>`:''}${hints>=2?`<p>提示二：回到這段找線索——${esc(s.text)}</p>`:''}${hints>=3?`<p>示範：${esc(s.choices[s.answer])}。${esc(s.result)} 請用自己的話連結證據；完成後可到「換情境再試」獨立練習。</p>`:''}${last?`<p>已記錄 ${attempts.length} 次嘗試；上次選擇${last.correct?'符合題意':'需要再想'}，選句${last.evidenceMatch?'來自這段':'請重新比對這段'}。理由保留給你和老師討論，不用關鍵字自動判分。</p>`:''}</section>`;
 }
 function extra(id){
  const t=getTown(),s=learningQuest(t,id),d=draft(id),c=LEARNING_CONTENT[id],variant=Number(d.variant??(s.reviews.length%2)),kind=d.reviewKind||'transfer',task=kind==='recall'?recallTask(id,variant):c.transfer[variant],last=s.revisions.at(-1),due=reviewDue(t,id);
  let teacherFeedback=null;try{const student=JSON.parse(localStorage.getItem('bianshui-learning-student-v1'));teacherFeedback=readStoredFeedback(localStorage,t,student?.id,id);}catch{}
  const prediction=id==='yueyang'?`<details class="learning-prediction"><summary>決策實驗：先預測，再觀察</summary><p>教學情境：有限物資要安排安置、糧食與修樓。這是遊戲改編，不是史實災情數據。</p>${s.prediction?`<p>我原先選：${s.prediction.choice==='care'?'先照顧住處與糧食':'先重修名樓'}。${esc(s.prediction.reason)}</p><p>情境推演：${s.prediction.choice==='care'?'基本需要先得到安排，修樓需要等候。':'樓的工程先開始，安置與供糧仍待安排。'}兩種安排都使用資源，請回到文章比較先後。</p><label>與我的預測有何不同？<textarea maxlength="400" ${field(id,'observation')}>${esc(d.observation??s.prediction.observation)}</textarea></label><button data-learning="observe" data-quest-id="${id}">保留觀察與反思</button>`:`<label>我先安排<select ${field(id,'predictionChoice')}><option value="care">住處與糧食</option><option value="tower" ${d.predictionChoice==='tower'?'selected':''}>重修名樓</option></select></label><label>我預測居民會……<textarea maxlength="400" ${field(id,'predictionReason')}>${esc(d.predictionReason||'')}</textarea></label><button data-learning="predict" data-quest-id="${id}">保留預測，再看情境推演</button>`}</details>`:'';
  return `${prediction}<details class="learning-transfer" ${due?'open':''}><summary>${due?'隔次複習到時間了・可略過':'換情境再試・不影響通關'}</summary><p>今天可以練習；隔一天再回來也會提醒。答案與理由分開記錄，不扣建築、不要求連續登入。</p><label>練習類型<select ${field(id,'reviewKind')}><option value="transfer" ${kind==='transfer'?'selected':''}>生活新情境</option><option value="recall" ${kind==='recall'?'selected':''}>回想原文</option></select></label><label>題目<select ${field(id,'variant')}>${c.transfer.map((_,i)=>`<option value="${i}" ${variant===i?'selected':''}>情境 ${i+1}</option>`).join('')}</select></label><p>${esc(task.prompt)}</p><fieldset><legend>我會怎麼做？</legend>${task.choices.map((text,i)=>`<label><input type="radio" name="learning-transfer-answer" value="${i}" ${field(id,'transferAnswer')} ${d.transferAnswer===String(i)?'checked':''}>${esc(text)}</label>`).join('')}</fieldset><label>說說理由<textarea maxlength="400" ${field(id,'transferReason')}>${esc(d.transferReason||'')}</textarea></label><button data-learning="transfer" data-quest-id="${id}">記錄這次練習</button>${s.reviews.at(-1)?`<p>上次${s.reviews.at(-1).kind==='recall'?'原文回憶':'生活遷移'}第${s.reviews.at(-1).variant+1}題：選擇${s.reviews.at(-1).correct?'符合本題原則':'可以再比較'}。${esc(s.reviews.at(-1).kind==='recall'?recallTask(id,s.reviews.at(-1).variant).why:c.transfer[s.reviews.at(-1).variant].why)} 理由待討論，沒有自動評定理解程度。</p>`:''}</details><details class="learning-portfolio"><summary>我的作品修改紀錄（${s.revisions.length} 版）</summary><p>保存初稿、回饋與修改原因。這裡與上方短箋分開保留；不會自動覆蓋短箋。最多保留最近12版，可從學習紀錄匯出。</p><label>作品文字<textarea maxlength="400" rows="3" ${field(id,'revisionText')}>${esc(d.revisionText??last?.text??t.journey?.literary?.[id]?.note??'')}</textarea></label>${last?`${teacherFeedback?`<p>已讀取 ${esc(teacherFeedback.teacher)} 對提交版本的回饋：${esc(teacherFeedback.comment)}</p>`:''}<label>收到的回饋或我的自我檢查<textarea maxlength="400" ${field(id,'feedback')}>${esc(d.feedback??teacherFeedback?.comment??'')}</textarea></label><label>我修改了什麼、為什麼<textarea maxlength="400" ${field(id,'changes')}>${esc(d.changes||'')}</textarea></label>`:''}<button data-learning="revision" data-quest-id="${id}">${last?'保留修改版本':'保留第一稿'}</button>${last?'<button data-learning="card" data-quest-id="'+id+'">下載圖文作品卡</button>':''}<ol>${s.revisions.map((r,i)=>`<li><strong>保留版本 ${i+1}</strong><p>${esc(r.text)}</p>${r.feedback?`<p>回饋：${esc(r.feedback)}</p><p>修改：${esc(r.changes)}</p>`:''}</li>`).join('')}</ol></details>`;
 }
 function input(event){const el=event.target,id=el.dataset.learningQuest;if(id&&el.dataset.learningField)draft(id)[el.dataset.learningField]=el.value;}
 function changed(event){const el=event.target;if(el.hasAttribute('data-learning-level')||el.hasAttribute('data-learning-zhuyin')){const p=learningState(getTown());const ok=change(t=>setReadingSupport(t,el.hasAttribute('data-learning-level')?el.value:p.level,el.hasAttribute('data-learning-zhuyin')?el.checked:p.zhuyin));say(ok?'閱讀支援已保存；原有進度保留。':'閱讀支援未變更或存檔未完成。');return;}if(['variant','reviewKind'].includes(el.dataset.learningField)){const d=draft(el.dataset.learningQuest);d[el.dataset.learningField]=el.value;delete d.transferAnswer;delete d.transferReason;say('換一個情境，再說說理由。');}}
 function click(event){const b=event.target.closest('[data-learning]');if(!b)return false;const action=b.dataset.learning,id=b.dataset.questId,step=Number(b.dataset.step),d=id?draft(id):{};
  if(action==='stop-speech'){window.speechSynthesis?.cancel();return true;}
  if(action==='speak'){if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){say('此裝置不支援朗讀，可以看原文與白話引導，或請老師一起讀。');return true;}window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(LITERARY_QUESTS[id].steps[step].text.split('\n')[Number(b.dataset.line)]);speech.lang='zh-TW';speech.rate=0.85;speech.onerror=()=>say('朗讀未完成，文字仍保留；可請老師一起讀。');window.speechSynthesis.speak(speech);return true;}
  if(action==='card'){const text=learningQuest(getTown(),id).revisions.at(-1)?.text;if(text){const url=URL.createObjectURL(new Blob([workCardSVG(id,LITERARY_QUESTS[id].name,text)],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='汴水小鎮-'+id+'-作品卡.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return true;}
  let ok=false,message='';
  if(action==='hint'){ok=change(t=>useLearningHint(t,id,step));message='線索已展開，使用提示也能繼續練習。';}
  if(action==='answer'){if(d.answer===undefined||!d.evidence||!d.reason?.trim()){say('先選答案、原文線索，再寫一句理由；也可和老師口述後一起記下。');return true;}ok=change(t=>recordLearningAnswer(t,id,{step,answer:Number(d.answer),evidence:Number(d.evidence),reason:d.reason}));if(ok){const a=learningQuest(getTown(),id).attempts.at(-1);message=a.correct&&a.evidenceMatch?'選擇與原文線索已記錄；理由保留待討論。進入下一段。':'這次想法已保留。請回看原文或使用線索，調整答案與證據。';if(a.correct&&a.evidenceMatch){delete d.answer;delete d.evidence;delete d.reason;}}}
  if(action==='revision'){ok=change(t=>saveLearningRevision(t,id,{text:d.revisionText??learningQuest(t,id).revisions.at(-1)?.text??t.journey?.literary?.[id]?.note??'',feedback:d.feedback??event.currentTarget.querySelector('[data-learning-field=feedback]')?.value??'',changes:d.changes||''}));message='作品版本已保留，可比較前後的想法。';}
  if(action==='transfer'){if(d.transferAnswer===undefined){say('先選擇一個做法，再說明理由。');return true;}d.variant??=String(learningQuest(getTown(),id).reviews.length%2);ok=change(t=>recordTransfer(t,id,{kind:d.reviewKind||'transfer',variant:Number(d.variant??(learningQuest(t,id).reviews.length%2)),answer:Number(d.transferAnswer),reason:d.transferReason||''}));message='練習已保存，理由留給你與老師討論。';}
  if(action==='predict'||action==='observe'){ok=change(t=>recordPrediction(t,id,{choice:d.predictionChoice||'care',reason:d.predictionReason||learningQuest(t,id).prediction?.reason||'',observation:d.observation||''}));message='預測與觀察已保留；最初的預測不會被改寫。';}
  say(ok?message:'尚未儲存：請補齊文字；修改稿需有回饋與修改原因，也請留意存檔通知。');return true;
 }
 return {reading,extra,input,changed,click,stop(){window.speechSynthesis?.cancel();}};
}
