// Public-domain originals. Punctuation follows the linked text; explanatory notes are game copy.
export const AUTHORS=[
 {id:'su',name:'蘇軾',era:'北宋',color:0x657f92,preferred:['wine','tea'],title:'水調歌頭・明月幾時有',form:'宋詞 · 全文',quote:'但願人長久，千里共嬋娟。',url:'https://zh.wikisource.org/zh-hant/水調歌頭_(明月幾時有)',intro:'原序寫「丙辰中秋，歡飲達旦，大醉，作此篇，兼懷子由」。詞由問月寫到思念與祝願；遊戲借河畔月色呈現這段文學想像。',text:'明月幾時有，把酒問青天。\n不知天上宮闕，今夕是何年。\n我欲乘風歸去，惟恐瓊樓玉宇，高處不勝寒。\n起舞弄清影，何似在人間。\n\n轉朱閣，低綺戶，照無眠。\n不應有恨，何事長向別時圓。\n人有悲歡離合，月有陰晴圓缺，此事古難全。\n但願人長久，千里共嬋娟。'},
 {id:'li',name:'李清照',era:'宋代',color:0xa27889,preferred:['pond','pavilion'],title:'聲聲慢・尋尋覓覓',form:'宋詞 · 全文',quote:'梧桐更兼細雨，到黃昏、點點滴滴。',url:'https://zh.wikisource.org/zh-hant/聲聲慢_(李清照)',intro:'疊字、雁影、黃花與雨聲層層寫出愁緒。這首詞不是輕快的遊園紀錄；小鎮以池畔停留與聽雨呼應意象，不推定原作寫成於汴京。',text:'尋尋覓覓，冷冷清清，悽悽慘慘戚戚。\n乍暖還寒時候，最難將息。\n三杯兩盞淡酒，怎敵它、晚來風急？\n雁過也，正傷心，卻是舊時相識。\n\n滿地黃花堆積。憔悴損，如今有誰堪摘？\n守著窗兒，獨自怎生得黑？\n梧桐更兼細雨，到黃昏、點點滴滴。\n這次第，怎一個愁字了得！'},
 {id:'xin',name:'辛棄疾',era:'南宋',color:0x617855,preferred:['wine','food'],title:'青玉案・元夕',form:'宋詞 · 全文',quote:'驀然回首，那人卻在，燈火闌珊處。',url:'https://zh.wikisource.org/zh-hant/青玉案_(辛棄疾)',intro:'由元夕燈市的繁華轉到人群之外的尋覓。遊戲讓他走過酒樓與街燈；並不把小鎮日常當成真實的元夕創作現場。',text:'東風夜放花千樹，更吹落、星如雨。\n寶馬雕車香滿路，鳳簫聲動，玉壺光轉，一夜魚龍舞。\n\n蛾兒雪柳黃金縷，笑語盈盈暗香去。\n眾裡尋他千百度；驀然回首，那人卻在，燈火闌珊處。'},
 {id:'fan',name:'范仲淹',era:'北宋',color:0x827757,preferred:['academy','pond'],title:'岳陽樓記',form:'文章 · 節錄末段',quote:'先天下之憂而憂，後天下之樂而樂。',url:'https://zh.wikisource.org/zh-hant/岳陽樓記',intro:'文章由洞庭景象推向古仁人的胸懷。此處節錄末段，保留「先憂後樂」的上下文；書院停筆是遊戲演出，並非作者在小鎮撰成此文。',text:'嗟夫！予嘗求古仁人之心，或異二者之為，何哉？不以物喜，不以己悲。\n\n居廟堂之高，則憂其民；處江湖之遠，則憂其君。是進亦憂，退亦憂；然則何時而樂耶？\n\n其必曰「先天下之憂而憂，後天下之樂而樂」歟！噫！微斯人，吾誰與歸？'},
 {id:'ouyang',name:'歐陽修',era:'北宋',color:0x937458,preferred:['pavilion','tea'],title:'醉翁亭記',form:'文章 · 節錄首段',quote:'醉翁之意不在酒，在乎山水之間也。',url:'https://zh.wikisource.org/zh-hant/醉翁亭記',intro:'原文地景在滁州琅琊山。節錄從環山寫到亭與山水之樂；遊戲的臨泉亭承接其意象，不等同史實中的醉翁亭。',text:'環滁皆山也。其西南諸峰，林壑尤美，望之蔚然而深秀者，琅琊也。山行六七里，漸聞水聲潺潺而瀉出於兩峰之間者，釀泉也。峰迴路轉，有亭翼然臨於泉上者，醉翁亭也。\n\n作亭者誰？山之僧智仙也。名之者誰？太守自謂也。太守與客來飲於此，飲少輒醉，而年又最高，故自號曰醉翁也。醉翁之意不在酒，在乎山水之間也。山水之樂，得之心而寓之酒也。'}
];
export const authorById=id=>AUTHORS.find(a=>a.id===id);
