import {gardenStatus} from './garden-services.js';
import {pollutionStatus} from './pollution.js';
import {educationStatus,educationOf} from './education.js';
import {healthcareStatus,healthcareReport} from './healthcare.js';
import {onSickLeave} from './employment.js';
import {fireStatus,repairFire,damaged,fireActionCost} from './fire-service.js';
import {waterStatus} from './water-service.js';
import {isUtility} from './public-services.js';
import {sanitationStatus} from './sanitation.js';
import {publicAccess} from './road-network.js';
import {residentCondition} from './city-growth.js';
import {shopStatus} from './commerce.js';
import {installFinanceUI} from './finance-ui.js';
import {buildCost,moveCost,upgradeCost,roadCost,affordable,managed} from './city-finance.js';
import {editTown} from './town-edit.js';
import {escapeHTML as escape,lotIdentity,lotButton,lotFocusButton,stallDetails,stallListItem} from './content-html.js';
import {RecoveryPoint} from './recovery.js';
import {installRuntimeRecovery} from './recovery-ui.js';
import {createRuntime} from './runtime.js';
import {SaveStore,SAVE_KEY} from './save-store.js';
import {validateSave} from './save-schema.js';
import {installSaveUI} from './save-ui.js';
import {tierOf,MAX_TIER,TIER_NAMES,TIER_DETAILS} from './building-tiers.js';
import {NEW_DESIGNS} from './variety.js';
import {marketStalls,marketOpen} from './market.js';
import {publicSquares,ROAD_TYPES,streetCells,footprint,freeCells,layRoad,removeRoad,moveBuilding,demolishBuilding,upgradeBuilding} from './urban.js';
import {AUTHORS,authorById} from './literati-data.js';
import {authorStatus} from './literati.js';
import {DESIGNS,SOURCES,designFor,squareCells} from './heritage.js';
import {setWeather} from './weather.js';
import {GOODS,RECIPES,at,placeName,locateLot} from './production.js';
import {courtyards} from './courtyards.js';
import './style.css';
import * as THREE from 'three';
import {TownScene} from './scene.js';
import {Soundscape} from './sound.js';
import {Town,TYPES,dragCells,CELL} from './simulation.js';
const $=s=>document.querySelector(s),canvas=$('#world'),sound=new Soundscape();let designFilter='all';let editing=null,undoTown=null,pendingDelete=null,editFailure='';let journalOpen=false,selectedDesign=null,plotSize=1;
const icons={explore:'<circle cx="16" cy="16" r="10"/><path d="m20 12-3 7-5 2 3-7 5-2Z"/>',home:'<path d="m3 14 13-9 13 9M6 14v13h20V14M12 27v-9h8v9M2 16h28M8 11v-4h4"/>',shop:'<path d="M5 14v13h22V14M3 13l3-7h20l3 7M3 13c0 5 7 5 7 0 0 5 6 5 6 0 0 5 6 5 6 0 0 5 7 5 7 0M10 27v-8h6v8M21 19h3"/>',work:'<path d="m7 5 6 1 4 5-5 5-5-4-2-5 3 3 4-4-5-1ZM15 14l12 12-3 3-12-12M21 4l6 6-5 5M21 6l-5 6M7 21l-4 5 3 3 5-4"/>'};
for(const el of document.querySelectorAll('[data-icon]'))el.innerHTML=`<svg viewBox="0 0 32 32" aria-hidden="true">${icons[el.dataset.icon]}</svg>`;
let town=new Town({mode:'managed'}),scene,mode='explore',speed=1,paused=false,drag=null,down=null,pinned=null,hovered=null,lastUi=0,lastSave=0,toastTimer,following=null,selectedLot=null;
const fixtureName=new URLSearchParams(location.search).get('fixture');const fixtureMode=import.meta.env.DEV&&['v4','v5','v6','v7','v8'].includes(fixtureName);
const owner=crypto.randomUUID();
const storage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value),key:i=>localStorage.key(i),get length(){return localStorage.length;}};
const storageTest=import.meta.env.DEV&&new URLSearchParams(location.search).has('storage-test');
const saveStore=new SaveStore({storage,validate:validateSave,owner,key:storageTest?'bianshui-town-test-v1':SAVE_KEY});let saveUI,recovery;
try{if(fixtureMode)town=Town.restore(await(await fetch(`/tests/fixtures/${fixtureName}-town.json`)).json());else{const loaded=saveStore.load();if(loaded.data)town=Town.restore(loaded.data);if(loaded.status==='recovery')paused=true;}}catch(error){saveStore.blocked='recovery';saveStore.error=error.message;paused=true;$('#save-status').textContent='存檔無法讀取 · 原檔保留，請開啟存檔管理';}

try{scene=new TownScene(canvas);}catch(error){$('#welcome').innerHTML='<h2>目前無法開啟 3D 場景</h2><p>請使用支援 WebGL 2 的瀏覽器，並開啟硬體加速後重新整理。</p>';console.error(error);throw error;}
if(town.buildings.length)$('#welcome').hidden=true;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function save(){if(recovery?.fault){$('#save-status').textContent='執行錯誤 · 已停止自動儲存';return;}if(fixtureMode){$('#save-status').textContent='預覽場景 · 不覆寫小鎮';return;}const result=saveStore.save(town.toJSON());$('#save-status').textContent=result.ok?'進度已留存':result.status==='conflict'?'另一分頁已有更新 · 請開啟存檔管理':result.status==='recovery'?'原存檔保留 · 自動儲存已停止':'儲存失敗 · 請匯出目前小鎮';if(result.status==='conflict'&&!paused){paused=true;saveUI?.open();}}

function setMode(next){editing=null;selectedDesign=null;$('#blueprint-status').hidden=true;scene.showBuildGrid(next!=='explore');if(next!=='explore')stopFollowing();mode=next;drag=null;scene.clearGroup(scene.preview);document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});scene.controls.mouseButtons.LEFT=mode==='explore'?THREE.MOUSE.PAN:undefined;scene.controls.touches.ONE=mode==='explore'?THREE.TOUCH.PAN:undefined;$('#mode-hint').textContent=mode==='explore'?'自由探索 · 拖曳移動畫面，點選屋舍與居民':`${ROAD_TYPES[mode]||TYPES[mode]||'調整街坊'} · 點選放置，橫拉最多四格；斜拉 2 × 2 自動合建；門前步道須以道路接至東側引道`;canvas.style.cursor=mode==='explore'?'grab':'crosshair';}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{setMode(b.dataset.mode);$('#welcome').hidden=true;};
$('#start-btn').onclick=()=>{$('#welcome').hidden=true;setMode('home');toast('在草地上點一下，安放第一間民居');};
$('#demo-btn').onclick=()=>{if(!applyUrban(draft=>{draft.city.mode='sandbox';draft.demo();return true;}))return;$('#welcome').hidden=true;setMode('explore');save();toast('歡迎來到汴水小鎮，點選屋舍看看誰在裡面');};
$('#pause-btn').onclick=()=>{paused=!paused;$('#pause-btn').textContent=paused?'▶':'Ⅱ';$('#pause-btn').classList.toggle('paused',paused);$('#pause-btn').setAttribute('aria-label',paused?'繼續':'暫停');};
$('#speed-btn').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speed-btn').textContent=`${speed}×`;};
$('#weather-btn').onclick=()=>{const next={auto:'rain',rain:'clear',clear:'auto'}[town.weather.mode];setWeather(town,next);save();};
$('#light-toggle').onclick=()=>{town.time=Math.floor(town.time/24)*24+((town.time%24>=6&&town.time%24<19)?21:9);save();};
$('#zoom-in').onclick=()=>{scene.camera.zoom=Math.min(3.2,scene.camera.zoom*1.2);scene.camera.updateProjectionMatrix();};
$('#zoom-out').onclick=()=>{scene.camera.zoom=Math.max(.6,scene.camera.zoom/1.2);scene.camera.updateProjectionMatrix();};
$('#reset-view').onclick=()=>{stopFollowing();scene.resetView();};
$('#sound-btn').onclick=async()=>{try{const on=await sound.toggle();$('#sound-btn').setAttribute('aria-pressed',String(on));$('#sound-btn').setAttribute('aria-label',on?'關閉環境音':'開啟環境音');$('#sound-btn').classList.toggle('sound-on',on);toast(on?'風聲、水聲與市井日常，慢慢聽':'環境音已關閉');}catch(e){toast(e.message);}};
$('#volume').oninput=e=>sound.setVolume(Number(e.target.value)/100);
$('#life-btn').onclick=()=>{journalOpen=!journalOpen;if(journalOpen&&innerWidth<600)pinned=hovered=null;$('#life-btn').setAttribute('aria-expanded',String(journalOpen));updateJournal();};
$('#life-panel').onclick=e=>{
 if(e.target.closest('[data-production]')){renderProduction();$('#production').showModal();return;}
 if(e.target.closest('[data-story-focus]')){
  const event=town.stories.active||town.stories.last;if(!event)return;stopFollowing();pinned=hovered=null;setMode('explore');scene.focusAt(event.center);toast(`${event.title} · ${event.venue}${town.stories.active?'':'（已散場）'}`);
 }else{const btn=e.target.closest('[data-focus]');if(!btn)return;stopFollowing();pinned=hovered=null;setMode('explore');scene.focusAt({bridge:[18,-16],dock:[12,8],town:[-7,0]}[btn.dataset.focus],1.8);}
 if(innerWidth<600){journalOpen=false;updateJournal();}
};
$('#concepts-btn').onclick=()=>$('#gallery').showModal();$('#help-btn').onclick=()=>$('#help').showModal();
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>document.getElementById(b.dataset.close).close();
$('#new-town').onclick=$('#reset-town').onclick=()=>$('#confirm-reset').showModal();
$('#confirm-new').onclick=()=>{const nextTown=new Town({mode:'managed'});if(!fixtureMode&&saveStore.blocked!=='recovery'){const result=saveStore.checkpoint(town.toJSON());if(!result.ok){toast('無法保留重置復原點，請先匯出小鎮');return;}}if(!fixtureMode){const result=saveStore.replace(nextTown.toJSON());if(!result.ok){toast('重置未完成，原小鎮仍保留；請先匯出進度');return;}}stopFollowing();undoTown=JSON.parse(JSON.stringify(town));town=nextTown;runtime.reset();recovery=new RecoveryPoint({read:()=>town.toJSON(),validate:validateSave});$('#undo-urban').hidden=false;paused=false;speed=1;$('#speed-btn').textContent='1×';$('#pause-btn').textContent='Ⅱ';$('#pause-btn').classList.remove('paused');$('#pause-btn').setAttribute('aria-label','暫停');down=drag=selectedLot=pendingDelete=null;scene.reset();scene.resetView();pinned=hovered=null;journalOpen=false;updateJournal();$('#inspector').hidden=true;$('#welcome').hidden=false;$('#confirm-reset').close();$('#help').close();setMode('explore');save();toast('小鎮已重置；存檔管理保留重置前小鎮');};
function cellAt(e){const p=scene.atScreen(e.clientX,e.clientY);return p?{x:Math.round(p.x/CELL),z:Math.round(p.z/CELL)}:null;}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{stopFollowing();if(e.button!==0)return;down={x:e.clientX,y:e.clientY};if(mode!=='explore'){const c=cellAt(e);if(c){const cells=plannedCells(c);drag={start:c,cells};scene.outline(cells,canPlan(cells)?0x668856:0xb5644c);canvas.setPointerCapture(e.pointerId);}}});
canvas.addEventListener('pointermove',e=>{if(mode!=='explore'){const c=cellAt(e);if(!c)return;const cells=editing?.kind==='road'?streetCells(drag?.start||c,c):editing?plannedCells(c):selectedDesign&&plotSize===4?plannedCells(c):drag?dragCells(drag.start,c):[c];if(drag)drag.cells=cells;scene.outline(cells,canPlan(cells)?0x668856:0xb5644c);return;}if(!down)hovered=scene.pick(e.clientX,e.clientY);});
canvas.addEventListener('pointerup',e=>{if(e.button!==0)return;if(drag&&editing){const op=editing,cells=drag.cells,squareCount=publicSquares(town).length;const success=applyUrban(draft=>op.kind==='move'?moveBuilding(draft,op.id,cells[0]):op.type==='erase'?removeRoad(draft,cells):layRoad(draft,op.type,cells));toast(success?(op.kind==='move'?'建築已搬移，住戶與貨物保留':publicSquares(town).length>squareCount?'四格道路已合成街坊廣場；可按復原撤銷':'公共道路已更新；可按復原撤銷'):editFailure||'這裡無法操作，請避開建築及範圍外地面');drag=null;scene.clearGroup(scene.preview);if(success&&op.kind==='move'){setMode('explore');pinned={kind:'building',id:op.id};}down=null;return;}if(drag){const placed=applyUrban(draft=>draft.place(mode,drag.cells,false,selectedDesign));if(placed){$('#welcome').hidden=true;const b=town.buildings.find(b=>b.blockId===placed.id);toast(`${b.footprint?'四格合建 · ':''}${b.name}開始${b.design==='pond'?'挖池':'動工'}`);save();if(selectedDesign){setMode('explore');pinned={kind:'building',id:b.id};hovered=null;}}else toast(editFailure||'這裡放不下，請選擇範圍內的空地；四格須完整空出 2 × 2');drag=null;scene.clearGroup(scene.preview);}else if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5){pinned=scene.pick(e.clientX,e.clientY);hovered=pinned;}down=null;});
canvas.addEventListener('pointercancel',()=>{drag=null;down=null;scene.clearGroup(scene.preview);});
canvas.addEventListener('pointerleave',()=>{hovered=null;if(!drag)scene.clearGroup(scene.preview);});
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();$('#pause-btn').click();}if(['1','2','3','4'].includes(e.key))setMode(['explore','home','shop','work'][Number(e.key)-1]);if(e.key==='Escape'){stopFollowing();setMode('explore');pinned=hovered=null;}if(e.key.toLowerCase()==='q')scene.rotate(-Math.PI/8);if(e.key.toLowerCase()==='e')scene.rotate(Math.PI/8);});
window.addEventListener('resize',()=>scene.resize());window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>runtime.visibility());
function formatTime(time){return `${String(Math.floor(time%24)).padStart(2,'0')}:${String(Math.floor(time%1*60)).padStart(2,'0')}`;}
function inspectorContent(panel,html){delete panel.dataset.person;delete panel.dataset.author;if(panel.dataset.content!==html){panel.innerHTML=html;panel.dataset.content=html;}}
function stopFollowing(){following=null;if(scene)scene.follow(null);$('#follow-status').hidden=true;}
$('#stop-follow').onclick=()=>stopFollowing();
$('#inspector').onclick=e=>{
 const manage=e.target.closest('[data-manage]');if(manage){const b=town.building(Number(manage.dataset.building));if(!b)return;const op=manage.dataset.manage;if(op==='fire'){toast(applyUrban(draft=>repairFire(draft,b.id))?'火警處置完成，建築恢復使用':editFailure||'金庫不足；整修倒數結束後會免費恢復');renderInspector();return;}if(op==='move'){setMode('move');editing={kind:'move',id:b.id};pinned=hovered=null;$('#mode-hint').textContent=`搬移${b.name} · 點選${b.footprint?'2 × 2':'一格'}空地 · Esc 取消`;return;}if(op==='delete'){pendingDelete=b.id;$('#demolish-name').textContent=`拆除「${b.name}」？住戶保留並等候新居，貨物退回貨棧。可使用「復原上一步」撤銷。`;$('#demolish').showModal();return;}const ok=applyUrban(draft=>upgradeBuilding(draft,b.id,op==='expand'));toast(ok?(op==='expand'?'四格擴建完成':`${town.building(b.id).name}升至 ${tierOf(town.building(b.id))} 級`):editFailure||(op==='expand'?'四格擴建須原位置右方、下方共 2 × 2 空出，且不占道路':'建築尚未落成或已達五級'));renderInspector();return;}

 const work=e.target.closest('[data-author-work]');if(work){showAuthorWork(work.dataset.authorWork);return;}
 const af=e.target.closest('[data-author-follow]');if(af){const id=af.dataset.authorFollow,key='author:'+id;if(following===key)stopFollowing();else{setMode('explore');following=key;pinned={kind:'author',id};scene.follow(key);$('#following-name').textContent=`跟著${authorById(id).name}散步`;$('#follow-status').hidden=false;}renderInspector();return;}

 const reading=e.target.closest('[data-reading]');if(reading){showLiterature(reading.dataset.reading);return;}
 const courtButton=e.target.closest('[data-courtyard]');if(courtButton){const block=town.blocks.find(b=>b.id===Number(courtButton.dataset.courtyard)),court=courtyards(block)[0];stopFollowing();setMode('explore');scene.focusAt([court.x,court.z],3,true);toast('共享院落 · 側門與晾曬空間');return;}
 const resident=e.target.closest('[data-resident]');if(resident){stopFollowing();pinned={kind:'person',id:Number(resident.dataset.resident)};renderInspector();return;}
 const follow=e.target.closest('[data-follow]');if(!follow)return;const id=Number(follow.dataset.follow);
 if(following===id)stopFollowing();else{setMode('explore');following=id;pinned={kind:'person',id};scene.follow(id);scene.camera.zoom=Math.max(scene.camera.zoom,1.8);scene.camera.updateProjectionMatrix();$('#following-name').textContent=`跟著${town.people.find(p=>p.id===id).name}過一天`;$('#follow-status').hidden=false;}
 renderInspector();
};
let outlined='';
function renderInspector(){
 const ref=pinned||hovered,panel=$('#inspector');if(ref&&innerWidth<600&&journalOpen){journalOpen=false;updateJournal();}if(!ref){panel.hidden=true;if(outlined){scene.clearGroup(scene.selection);outlined='';}return;}
 panel.hidden=false;
 if(ref.kind==='building'){
  const b=town.building(ref.id);if(!b){panel.hidden=true;return;}const block=town.blocks.find(g=>g.id===b.blockId),res=town.residents(b),workers=town.workers(b),inside=town.occupants(b),stages=['整地打基礎','木架搭建中','覆瓦砌牆中','已落成','生活漸豐'];
  inspectorContent(panel,`<div class="eyebrow">${isUtility(b)?'公共設施':TYPES[b.type]} · ${b.footprint?'四格合建 · '+(b.type==='garden'?'一處園景':'一座建築'):block.cells.length+' 格街坊'}</div><h2>${escape(b.name)}</h2><div class="sub">${b.design==='pond'&&b.stage<3?['開挖池床','整修池岸','注水植荷'][b.stage]:stages[b.stage]}${pinned?' · 已固定檢視':''}</div>${b.stage<3?`<div class="progress"><i style="width:${Math.min(100,(town.elapsed-b.born)/18*100)}%"></i></div><p>${b.design==='pond'?'池床開挖、修岸與注水植荷依序進行。':'工匠正在'+stages[b.stage]+'，靜候落成。'}</p>`:`<hr><label>${isUtility(b)?'公共設施':b.type==='garden'?'園中漫步':b.type==='home'?'住在這裡':'在此工作'}</label><div>${(b.type==='garden'?inside:b.type==='home'?res:workers).map(p=>`<button class="tag" data-resident="${escape(p.id)}">${escape(p.name)} ↗</button>`).join('')||(isUtility(b)?'<span class="sub">自動服務，不需指派居民</span>':'<span class="sub">等候新朋友到來</span>')}</div>${courtyards(block).length>0?`<p>共享院落 · ${courtyards(block).length} 處相通庭院</p><button class="tag" data-courtyard="${escape(block.id)}">看看院落 ↗</button>`:''}${b.type==='work'?`<label>作坊進度</label><p>${escape(b.productionStatus||'等候原料')} · 原料 ${at(town,`input:${b.id}`).length} 份 · 成品 ${at(town,`output:${b.id}`).length} 件</p>`:''}${b.type==='shop'?`<label>河運補貨</label><p>${escape(shopStatus(town,b))}</p><p>店內 ${escape(b.stock||0)} 件 · 店前 ${town.life.visitors.filter(v=>v.visible&&v.target===b.id&&!v.walking).length} 位來客</p>`:''}<label>此刻在場 · ${inside.length} 人</label><p>${inside.length?inside.map(p=>`${escape(p.name)} · ${escape(p.action)}`).join('<br>'):'目前無人在此停留'}</p>`}${managed(town)?`<p>${publicAccess(town,b)?'道路已接通河岸貨棧':'街坊未接外路：請由門前步道鋪路至東側引道，才能接貨與迎接新住戶。'}</p>`:''}${waterStatus(town,b)?`<section class="water-status"><label>街坊供水</label><p>${escape(waterStatus(town,b))}</p></section>`:''}${sanitationStatus(town,b)?`<section class="sanitation-status"><label>衛生清運</label><p>${escape(sanitationStatus(town,b))}</p></section>`:''}${fireStatus(town,b)?`<section class="fire-status"><label>防火巡守</label><p>${escape(fireStatus(town,b))}</p>${b.fireWarningAt!==undefined||damaged(b)?`<button data-manage="fire" data-building="${escape(b.id)}">${b.fireWarningAt!==undefined?'排除火警':'立即修復'} · ${managed(town)?fireActionCost(b)+'文':'免費'}</button>`:''}</section>`:''}${healthcareStatus(town,b)?`<section class="healthcare-status"><label>藥鋪醫療</label><p>${escape(healthcareStatus(town,b))}</p></section>`:''}${educationStatus(town,b)?`<section class="education-status"><label>書院教育</label><p>${escape(educationStatus(town,b))}</p></section>`:''}${pollutionStatus(town,b)?`<section class="pollution-status"><label>生產污染與居住環境</label><p>${escape(pollutionStatus(town,b))}</p></section>`:''}${gardenStatus(town,b)?`<section class="garden-status"><label>園景宜居</label><p>${escape(gardenStatus(town,b))}</p></section>`:''}${buildingTools(b)}${literatureLink(b)}<hr><div class="sub">${pinned?'點選空地取消固定':'點選屋舍可固定這張小卡'}</div>`);
  const code='b'+block.id;if(outlined!==code){scene.outline(block.cells,0xd1b57b,scene.selection);outlined=code;}
 }else if(ref.kind==='stall'){
  const s=marketStalls(town).find(s=>s.id===ref.id);if(!s){panel.hidden=true;return;}inspectorContent(panel,stallDetails(s,town.market.trades,marketOpen(town)));if(outlined){scene.clearGroup(scene.selection);outlined='';}
 }else if(ref.kind==='author'){

  const a=authorById(ref.id),actor=town.literati.actors.find(v=>v.author===ref.id);if(!a){panel.hidden=true;return;}
  if(panel.dataset.author!==a.id){panel.innerHTML=`<div class="eyebrow">${a.era} · 文人行旅</div><h2>${a.name}</h2><p id="author-status"></p><button class="primary" data-author-follow="${a.id}"></button><hr><label>${a.title}</label><blockquote>${a.quote}</blockquote><button class="tag" data-author-work="${a.id}">讀代表作 ↗</button><p class="fine">跨年代文學相遇 · 落筆為遊戲演出</p>`;panel.dataset.author=a.id;delete panel.dataset.content;delete panel.dataset.person;}
  $('#author-status').textContent=authorStatus(town,actor)+(actor?.phase==='writing'&&!town.weather.raining?` · ${Math.min(100,Math.floor(actor.progress/12*100))}%`:'');
  const btn=panel.querySelector('[data-author-follow]');btn.textContent=following==='author:'+a.id?'停止跟隨':'跟著散步';btn.disabled=!actor?.visible;btn.setAttribute('aria-pressed',String(following==='author:'+a.id));
  if(outlined){scene.clearGroup(scene.selection);outlined='';}
 }else if(ref.kind==='life'){

  const a=[...town.life.visitors,...town.life.porters,...town.life.oxen].find(a=>a.id===ref.id);if(!a){panel.hidden=true;return;}inspectorContent(panel,`<div class="eyebrow">${({ox:'牛車運送',porter:'碼頭腳夫',peddler:'挑擔行商',traveler:'過橋旅人',shopper:'趕集來客'})[a.kind]}</div><h2>${escape(a.name)}</h2><p>${escape(a.traffic||a.action)}</p><hr><label>此刻攜帶</label><p>${a.kind==='peddler'?'挑擔與日用雜貨':a.carrying?at(town,`${a.kind==='ox'?'ox':'porter'}:${a.id}`).map(l=>GOODS[l.good]).join('、'):'輕裝行走'}</p><label>行程</label><p>${a.walking?'正在沿街道前往目的地':'停留、歇腳或等候'}</p>`);if(outlined){scene.clearGroup(scene.selection);outlined='';}
 }else if(ref.kind==='boat'){
  const b=town.life.boat;inspectorContent(panel,`<div class="eyebrow">汴河水運 · 第 ${b.trips+1} 航次</div><h2>汴河漕船</h2><p>${boatStatus()}</p><hr><label>船上貨物</label><p>${escape(b.cargo)} 件，${b.mast?'桅杆升起':'已收桅，準備過橋'}</p><label>本鎮累計</label><p>已卸 ${escape(town.life.dock.received)} 件 · 已送商鋪 ${escape(town.life.dock.delivered)} 件</p>`);if(outlined){scene.clearGroup(scene.selection);outlined='';}
 }else{
  const p=town.people.find(p=>p.id===ref.id);if(!p){panel.hidden=true;return;}const home=town.building(p.home),work=town.building(p.work),dest=town.building(p.destination);
  if(panel.dataset.person!==String(p.id)){
   panel.innerHTML=`<div class="eyebrow">街巷人物 · 一個人的日常</div><h2 id="person-name"></h2><p id="person-action"></p><button class="primary" id="follow-btn" data-follow="${escape(p.id)}"></button><hr><label>住處 · 工作場所</label><p id="person-place"></p><label>當下目的地</label><p id="person-goal"></p><label>今日記事 · 最新在上</label><ol id="person-diary" class="life-events"></ol>`;panel.dataset.person=String(p.id);delete panel.dataset.author;delete panel.dataset.content;
  }
  $('#person-name').textContent=p.name;$('#person-action').textContent=(p.traffic||p.action)+((p.needsSatisfiedUntil||0)>town.elapsed?' · 日用品已備妥':'')+' · '+residentCondition(p)+` · 學力 ${educationOf(p).toFixed(1)}／100 · 健康 ${Math.floor(p.health??100)}／100${onSickLeave(town,p)?' · 病假休養':''}${healthcareReport(town).assigned.has(p.id)?' · 接受藥鋪照護':''}`;
  $('#person-place').textContent=`${home?.name||'尚未安排'} · ${work?.name||'尚待安排'}`;
  $('#person-goal').textContent=p.streetEvent?`${town.stories.active?.venue||'街口'} · ${town.stories.active?.title||'街坊相聚'}`:dest?.name||'暫無目的地';
  $('#follow-btn').textContent=following===p.id?'停止跟隨':'跟著他過一天';$('#follow-btn').setAttribute('aria-pressed',String(following===p.id));
  const diary=(p.diary||[]).map(e=>`<li><time>${formatTime(e.time)}</time><span>${escape(e.text)}</span></li>`).join('')||'<li>等一段日常慢慢發生。</li>';
  if($('#person-diary').innerHTML!==diary)$('#person-diary').innerHTML=diary;
  if(outlined){scene.clearGroup(scene.selection);outlined='';}
 }
}
function updateUI(day){const incident=town.buildings.find(b=>b.fireWarningAt!==undefined)||town.buildings.find(damaged);$('#fire-alert').hidden=!incident;if(incident)$('#fire-alert').textContent=`${incident.fireWarningAt!==undefined?'火警預警':'整修中'}：${incident.name} · 點此查看`;if(following!=null&&!town.people.some(p=>p.id===following)&&!String(following).startsWith('author:'))stopFollowing();financeUI.update();$('#weather-btn').textContent=`${town.weather.raining?'細雨':'晴天'} · ${{auto:'自然',rain:'手動',clear:'手動'}[town.weather.mode]}`;$('#weather-btn').setAttribute('aria-label',`天候：${town.weather.raining?'細雨':'晴天'}，${{auto:'自然',rain:'手動',clear:'手動'}[town.weather.mode]}模式`);const h=town.time%24,hh=Math.floor(h),mm=Math.floor((h-hh)*60);$('#clock').textContent=`第 ${Math.floor(town.time/24)+1} 日　${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`;const shichen=['子','丑','寅','卯','辰','巳','午','未','申','酉','戌','亥'][Math.floor(((h+1)%24)/2)];$('#period').textContent=`${shichen}時 · ${h<6?'萬籟俱寂':h<10?'晨光初醒':h<16?'日光正好':h<19?'炊煙漸起':'燈火可親'}`;$('#sun-icon').textContent=day>.5?'☀':'☾';$('#light-toggle').textContent=day>.5?'☾':'☀';document.body.classList.toggle('night',day<.4);$('#population').textContent=town.people.length;$('#building-count').textContent=town.buildings.length;$('#block-count').textContent=town.blocks.length;renderInspector();}
function boatStatus(){const b=town.life.boat;return b.state==='approach'?(b.mast?'貨船沿汴河駛來':'船家收桅，緩緩穿過虹橋'):({mooring:'船家正在靠岸繫纜',unloading:'腳夫往返船邊卸貨',depart:'卸貨完成，貨船離岸',away:'等候下一艘來船'})[b.state];}
function updateJournal(){
 const panel=$('#life-panel');$('#life-btn').setAttribute('aria-expanded',String(journalOpen));panel.hidden=!journalOpen;if(!journalOpen)return;const l=town.life;
 if(!panel.querySelector('.watch-buttons'))panel.innerHTML=`<div class="eyebrow">此時此地 · 活著的市井</div><h2>汴水有消息</h2><p class="boat-status"></p><div class="life-numbers"><span><b id="j-visitors"></b> 來客</span><span><b id="j-stock"></b> 件待運</span><span><b id="j-delivered"></b> 件送達</span></div><div class="watch-buttons"><button data-focus="bridge">虹橋看船 ↗</button><button data-focus="dock">碼頭卸貨 ↗</button><button data-focus="town">回到街坊 ↗</button></div><button class="production-link" data-production>物產流轉 · 追蹤貨物 ↗</button><div id="street-story"><strong id="story-title"></strong><p id="story-description"></p><button data-story-focus>去街口看看 ↗</button></div><ol class="life-events"></ol>`;
 panel.querySelector('.boat-status').textContent=town.buildings.length?boatStatus():'先安放街坊，等市井生活長出來';
 $('#j-visitors').textContent=l.visitors.filter(a=>a.visible).length;$('#j-stock').textContent=l.dock.stock;$('#j-delivered').textContent=l.dock.delivered;
 const event=town.stories.active||town.stories.last;
 $('#story-title').textContent=event?.title||'街頭暫歇';$('#story-description').textContent=event?`${event.venue} · ${town.stories.active?(event.phase==='active'?'正在相聚':'街坊陸續到來'):'上一場已散場，可回看地點'}`:'等下一段相遇';
 panel.querySelector('[data-story-focus]').disabled=!event;
 const events=town.events.slice(0,5).map(e=>`<li><time>${String(Math.floor(e.time%24)).padStart(2,'0')}:${String(Math.floor(e.time%1*60)).padStart(2,'0')}</time><span>${escape(e.text)}</span></li>`).join('');
 const list=panel.querySelector('.life-events');if(list.dataset.content!==events){list.innerHTML=events;list.dataset.content=events;}
}
for(const [value,label] of Object.entries(GOODS))$('#goods-filter').add(new Option(label,value));$('#goods-filter').onchange=()=>renderProduction();
function renderProduction(){
 const overview=RECIPES.map(r=>{const works=town.buildings.filter(b=>b.type==='work'&&b.variant===RECIPES.indexOf(r));return `<article class="production-card"><h3>${GOODS[r.input]} → ${GOODS[r.output]}</h3><p>原料 ${town.economy.lots.filter(l=>l.good===r.input).length} 份 · 成品 ${town.economy.lots.filter(l=>l.good===r.output&&l.at!=='sold').length} 件 · 售出 ${escape(town.economy.sold[r.output]||0)} 件</p><p>${works.length?works.map(b=>`${escape(b.name)}：${escape(b.productionStatus||'等候工匠與原料')}`).join('<br>'):'先安放對應作坊，再等工匠到來'}</p></article>`;}).join('');$('#production-overview').innerHTML=overview;
 const filter=$('#goods-filter').value;const lots=town.economy.lots.filter(l=>filter==='all'||l.good===filter).sort((a,b)=>(a.at==='sold')-(b.at==='sold')||(!!b.madeAt)-(!!a.madeAt)||b.id-a.id);
 $('#lot-list').innerHTML=lots.map(l=>lotButton(l,placeName(town,l.at))).join('')||'<p>等一艘載貨的船到來。</p>';
 if(!lots.some(l=>l.id===selectedLot))selectedLot=lots[0]?.id;renderLot();
}
function renderLot(){
 const l=town.economy.lots.find(l=>l.id===selectedLot);if(!l){$('#lot-detail').innerHTML='';return;}
 $('#lot-detail').innerHTML=`<h3>${lotIdentity(l)}</h3><p>來源：${escape(l.origin)}${l.madeAt?` · 製作：${escape(town.building(l.madeAt)?.name)}`:''}</p><ol class="cargo-trail">${l.trailOmitted?`<li>較早的 ${escape(l.trailOmitted)} 筆紀錄已收進摘要；來源與製作紀錄仍保留。</li>`:''}${l.trail.map(step=>`<li>第 ${Math.floor(step.time/24)+1} 日 ${formatTime(step.time)} · ${escape(placeName(town,step.at))}</li>`).join('')}</ol>${locateLot(town,l)?lotFocusButton(l):'<p>這件貨已由來客購得。</p>'}`;
}
$('#production').onclick=e=>{const select=e.target.closest('[data-lot]');if(select){selectedLot=Number(select.dataset.lot);renderLot();return;}const focus=e.target.closest('[data-lot-focus]');if(!focus)return;const lot=town.economy.lots.find(l=>l.id===Number(focus.dataset.lotFocus)),location=lot&&locateLot(town,lot);if(!location)return;$('#production').close();journalOpen=false;updateJournal();stopFollowing();setMode('explore');pinned=location.ref||null;hovered=null;scene.focusAt(location.point,2.6);toast(`${GOODS[lot.good]} · ${placeName(town,lot.at)}`);};
recovery=new RecoveryPoint({read:()=>town.toJSON(),validate:validateSave});
const showRuntimeError=installRuntimeRecovery({getRecovery:()=>recovery,store:saveStore,fixtureMode});
const faultInjection=import.meta.env.DEV&&(fixtureMode||storageTest)?new URLSearchParams(location.search).get('runtime-fault'):null;let faultTicks=0;
const runtime=createRuntime({
 request:fn=>requestAnimationFrame(fn),cancel:id=>cancelAnimationFrame(id),hidden:()=>document.hidden,
 options:()=>({speed,paused:paused||!!document.querySelector('dialog[open]')}),tick:dt=>{town.tick(dt);if(faultInjection==='tick'&&++faultTicks===3){town.time=NaN;throw Error('測試：模擬更新中斷');}},
 mute:()=>sound.update(town,true),onHide:save,onError:showRuntimeError,
 render:(dt,now,isPaused)=>{const day=scene.update(town,dt);if(faultInjection==='render')throw Error('測試：畫面更新中斷');sound.update(town,isPaused);if(now-lastUi>180){updateUI(day);updateJournal();lastUi=now;}recovery.checkpoint(now);if(now-lastSave>12000){save();lastSave=now;}}
});
// Read-only diagnostics allow reproducible interaction checks without modifying simulation state.
window.__townDebug={follow:()=>({id:following,target:scene.controls.target.toArray()}),screenPerson:id=>{const model=scene.personModels.get(id);if(!model?.visible)return null;const p=model.position.clone().add(new THREE.Vector3(0,.55,0)).project(scene.camera);return {x:(p.x+1)/2*innerWidth,y:(1-p.y)/2*innerHeight};},snapshot:()=>JSON.parse(JSON.stringify(town)),screenCell:(x,z)=>{const p=new THREE.Vector3(x*4,0,z*4).project(scene.camera);return {x:(p.x+1)/2*innerWidth,y:(1-p.y)/2*innerHeight};},screenBuilding:id=>{const b=town.building(id);if(!b)return null;const p=new THREE.Vector3(b.x*4,1,b.z*4).project(scene.camera);return {x:(p.x+1)/2*innerWidth,y:(1-p.y)/2*innerHeight};},renderInfo:()=>({...scene.renderer.info.render}),mode:()=>mode,sound:()=>({enabled:sound.enabled,state:sound.ctx?.state||'not-started',gain:sound.master?.gain.value||0,volume:sound.volume}),screenLife:id=>{const a=[...town.life.visitors,...town.life.porters,...town.life.oxen].find(a=>a.id===id);if(!a)return null;const p=new THREE.Vector3(a.x,1,a.z).project(scene.camera);return {x:(p.x+1)/2*innerWidth,y:(1-p.y)/2*innerHeight};}};

function plannedCells(c){if(editing?.kind==='move')return town.building(editing.id)?.footprint?squareCells(c):[c];if(editing)return [c];return selectedDesign&&plotSize===4?squareCells(c):[c];}
function literatureLink(b){const d=DESIGNS[designFor(b)];if(!d?.source)return '';const source=SOURCES[d.source];return `<section class="literary-note"><small>${escape(source.author)} · ${escape(source.title)}</small><blockquote>${escape(source.quote)}</blockquote><button class="tag" data-reading="${d.source}">讀作品與地景 ↗</button></section>`;}
function showLiterature(id){const s=SOURCES[id];if(!s)return;$('#literature-title').textContent=s.title;$('#literature-body').innerHTML=`<p class="source-author">${escape(s.author)} · ${escape(s.era)}</p><blockquote>${escape(s.quote)}</blockquote><h3>文字如何長成風景</h3><p>${escape(s.note)}</p><a href="${s.url}" target="_blank" rel="noopener noreferrer">閱讀原文出處 ↗</a><p class="fine">引文為公版古典作品。建築名稱與造型為遊戲設計。</p>`;$('#literature').showModal();}
const planArt=id=>{const common='<path d="M15 81H145" stroke="#8f9477" stroke-width="2"/>';const roof=(x,y,w)=>`<path d="M${x} ${y+15}L${x+10} ${y+4}L${x+w-10} ${y+4}L${x+w} ${y+15}Z" fill="#586b68"/><path d="M${x+12} ${y+16}V80M${x+w-12} ${y+16}V80" stroke="#826345" stroke-width="4"/>`;let art='';if(id==='cleaningYard')art=roof(20,8,120)+'<path d="M30 58H125V76H30Z" fill="#826345"/><circle cx="45" cy="79" r="9" fill="#454536"/><circle cx="111" cy="79" r="9" fill="#454536"/><path d="M50 44H68V60H50ZM80 44H98V60H80Z" fill="#65775a"/>';else if(id==='well')art=roof(25,8,110)+'<ellipse cx="80" cy="70" rx="32" ry="12" fill="#b9b294"/><ellipse cx="80" cy="67" rx="23" ry="8" fill="#325e60"/><path d="M80 34V67M38 37H122" stroke="#826345" stroke-width="4"/>';else if(id==='garden')art='<path d="M20 65H140M80 30V85" stroke="#b6a987" stroke-width="10"/><circle cx="48" cy="48" r="17" fill="#8c9c69"/><circle cx="110" cy="48" r="17" fill="#8c9c69"/><circle cx="48" cy="45" r="6" fill="#d5a194"/><circle cx="110" cy="45" r="6" fill="#d9c379"/>';else if(DESIGNS[id]?.type==='home')art=roof(25,5,110)+roof(20,40,120)+'<path d="M40 40H120M50 30V40M75 30V40M100 30V40" stroke="#a47d52" stroke-width="3"/>';else if(DESIGNS[id]?.type==='work')art=roof(20,15,120)+'<path d="M28 55H130V80H28Z" fill="#9c815e"/><path d="M44 55V30H58V55" fill="#a07357"/>';else if(id==='pond')art='<ellipse cx="80" cy="64" rx="60" ry="17" fill="#78a59a"/><path d="M74 64V44M99 66V50" stroke="#778950" stroke-width="2"/><ellipse cx="63" cy="66" rx="18" ry="5" fill="#829e67"/><path d="M62 45Q74 22 85 45Q74 59 62 45" fill="#c89391"/>';else if(id==='wine')art=roof(24,5,112)+roof(16,39,128)+'<path d="M31 39H127M31 29H127M40 28V40M56 28V40M73 28V40M90 28V40M108 28V40" stroke="#a47d52" stroke-width="3"/>';else if(id==='academy')art=roof(38,12,84)+roof(9,47,42)+roof(109,47,42)+'<path d="M61 70H100V82H61Z" fill="#80a49a"/>';else if(id==='pavilion')art='<path d="M24 39L80 10L137 39L115 47H45Z" fill="#586b68"/><path d="M45 44V80M80 44V80M115 44V80" stroke="#8a6744" stroke-width="4"/>';else if(id==='textile')art=roof(25,7,110)+'<path d="M38 41H64V78H38Z" fill="#ac7673"/><path d="M66 41H92V78H66Z" fill="#82a3a1"/><path d="M94 41H120V78H94Z" fill="#c3ad7a"/>';else if(id==='food')art=roof(20,20,120)+'<path d="M39 30V9H51V30" fill="#9d8b71"/><path d="M24 49H136L145 61H15Z" fill="#b68c67"/><path d="M49 79V67H108V79" fill="#b89a6d"/>';else art=roof(15,20,78)+roof(82,39,63)+'<ellipse cx="104" cy="69" rx="19" ry="5" fill="#a58c66"/><path d="M104 70V80" stroke="#826345" stroke-width="3"/>';return `<svg viewBox="0 0 160 92" aria-hidden="true">${common}${art}</svg>`;};
function renderBlueprints(){document.querySelectorAll('[data-design-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.designFilter===designFilter)));document.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.size)===plotSize)));$('#blueprint-grid').innerHTML=Object.entries(DESIGNS).filter(([id,d])=>designFilter==='all'||designFilter==='new'&&!!NEW_DESIGNS[id]||d.type===designFilter).map(([id,d])=>`<article class="blueprint-card">${planArt(id)}<div><h3>${d.name}</h3><p>${d.detail}</p><small>${d.source?SOURCES[d.source].author+' · '+SOURCES[d.source].title:'宋式街坊 · 遊戲建築設計'}</small></div><button data-plan="${id}">${d.sizes.includes(plotSize)?(plotSize===4?'四格合建':d.sizes.includes(4)?'點蓋／拖曳合建':'一格營造'):'使用'+(d.sizes.includes(4)?'四格合建':'一格營造')}${id==='pond'?' · 挖池塘':''} ↗</button></article>`).join('');}
$('#blueprints-btn').onclick=()=>{renderBlueprints();$('#blueprints').showModal();};
$('#blueprints').onclick=e=>{const filter=e.target.closest('[data-design-filter]');if(filter){designFilter=filter.dataset.designFilter;renderBlueprints();return;}const size=e.target.closest('[data-size]');if(size){plotSize=Number(size.dataset.size);renderBlueprints();return;}const plan=e.target.closest('[data-plan]');if(!plan)return;const d=DESIGNS[plan.dataset.plan];if(!d.sizes.includes(plotSize))plotSize=d.sizes[0];setMode(d.type);selectedDesign=plan.dataset.plan;pinned=hovered=null;journalOpen=false;updateJournal();$('#blueprint-status').textContent=`${d.name} · ${plotSize===4?'四格合建':'一格小築'}`;$('#blueprint-status').hidden=false;$('#mode-hint').textContent=`${d.name} · 點選${plotSize===4?'完整的 2 × 2':'一格'}空地${d.type==='garden'?'營造園景':'開始動工'} · Esc 取消`;$('#welcome').hidden=true;$('#blueprints').close();};

function showAuthorWork(id){const a=authorById(id);if(!a)return;$('#author-work-title').textContent=a.title;$('#author-work-body').innerHTML=`<p class="source-author">${a.name} · ${a.era} · ${a.form}</p><div class="original-work">${escape(a.text)}</div><hr><p>${escape(a.intro)}</p><a href="${a.url}" target="_blank" rel="noopener noreferrer">閱讀原文出處 ↗</a><p class="fine">宋代公版原文。跨年代的行旅與落筆為遊戲演出。</p>`;$('#author-work').showModal();}
function renderWriters(){const list=town.literati.collected;$('#writers-count').textContent=`汴水文集 · 已落筆 ${list.length} / ${AUTHORS.length} 篇`;$('#writers-list').innerHTML=AUTHORS.map(a=>{const actor=town.literati.actors.find(v=>v.author===a.id),entry=list.find(v=>v.author===a.id);return `<article class="writer-card"><small>${a.era} · ${a.form}</small><h3>${a.name}</h3><p>${a.title}</p><p class="writer-state">${escape(authorStatus(town,actor))}</p><p class="fine">${entry?`已收入文集 · ${escape(entry.venue)} · 第 ${Math.floor(entry.time/24)+1} 日 ${formatTime(entry.time)}`:'晴天停步落筆後收入文集，代表作隨時可讀。'}</p><div><button data-author-focus="${a.id}" ${actor?.visible?'':'disabled'}>去找${a.name} ↗</button><button data-author-work="${a.id}">讀代表作</button></div></article>`;}).join('');}
$('#writers-btn').onclick=()=>{renderWriters();$('#writers').showModal();};
$('#writers').onclick=e=>{const work=e.target.closest('[data-author-work]');if(work){showAuthorWork(work.dataset.authorWork);return;}const focus=e.target.closest('[data-author-focus]');if(!focus)return;const a=town.literati.actors.find(v=>v.author===focus.dataset.authorFocus);if(!a?.visible)return;$('#writers').close();stopFollowing();setMode('explore');journalOpen=false;updateJournal();pinned={kind:'author',id:a.author};hovered=null;scene.focusAt([a.x,a.z],2.8);renderInspector();};

function plannedCost(cells){if(editing?.kind==='move')return moveCost(town.building(editing.id));if(editing)return editing.type==='erase'?0:roadCost(town,editing.type,cells);return buildCost(mode,cells);}
function canPlan(cells){const cost=plannedCost(cells);if(managed(town))$('#mode-hint').textContent=`本次 ${cost} 文 · 金庫 ${town.city.treasury} 文${affordable(town,cost)?'':' · 金額不足'}`;else $('#mode-hint').textContent='自由營造 · 本次不扣款';if(!affordable(town,cost))return false;if(!editing)return town.canPlace(cells);if(editing.kind==='move')return freeCells(town,cells,editing.id);if(editing.type==='erase')return cells.some(c=>town.publicWorks.some(p=>p.x===c.x&&p.z===c.z));return freeCells({...town,publicWorks:[]},cells);}
function applyUrban(fn){
 editFailure='';
 const editFault=import.meta.env.DEV&&(fixtureMode||storageTest)&&new URLSearchParams(location.search).get('edit-fault')==='refresh';
 const result=editTown(town,draft=>{if(editFault)draft.rebuildRoads=()=>{throw Error('測試：城市道路更新中斷');};return fn(draft);},{prepare:draft=>{scene.reset();scene.update(draft,0);},persist:data=>fixtureMode?{ok:true}:saveStore.save(data)});
 if(!result.ok){if(result.error){editFailure='操作未完成，原小鎮與進度仍保留。';$('#save-status').textContent=editFailure;toast(editFailure);try{scene.reset();}catch{showRuntimeError(result.error);}}return false;}
 town=result.town;undoTown=result.before;runtime.reset();recovery=new RecoveryPoint({read:()=>town.toJSON(),validate:validateSave});$('#undo-urban').hidden=false;if(drag)canPlan(drag.cells);$('#save-status').textContent=fixtureMode?'預覽場景 · 不覆寫小鎮':'進度已留存';return result.result;
}
function buildingTools(b){if(b.stage<3)return '';const tier=tierOf(b);return `<hr><label>建築 ${tier}／${MAX_TIER} 級 · ${TIER_NAMES[tier-1]}${b.type==='home'?` · 可住 ${b.footprint?8:b.level>=2?4:2} 人`:b.type==='work'?` · 加工 ${b.footprint?'2':b.level>=2?'1.5':'1'} 倍`:''}</label><p class="tier-detail">${tier<MAX_TIER?`下級：${TIER_DETAILS[tier]}`:'已達五級 · 盛景落成'}</p><div class="building-tools"><button data-manage="move" data-building="${escape(b.id)}">搬移 ${managed(town)?moveCost(b)+'文':''}</button><button data-manage="delete" data-building="${escape(b.id)}">拆除</button>${tier<MAX_TIER?`<button data-manage="upgrade" data-building="${escape(b.id)}">升至 ${tier+1} 級${managed(town)?' · '+upgradeCost(b)+'文':''}</button>`:''}${['home','work'].includes(b.type)&&!b.footprint?`<button data-manage="expand" data-building="${escape(b.id)}">四格擴建${managed(town)?' · '+upgradeCost(b,true)+'文':''} ↘</button>`:''}</div>`;}

$('#public-btn').onclick=()=>$('#public-works').showModal();
$('#public-works').onclick=e=>{const b=e.target.closest('[data-road]');if(!b)return;$('#public-works').close();setMode('road');editing={kind:'road',type:b.dataset.road};pinned=hovered=null;$('#welcome').hidden=true;$('#mode-hint').textContent=`${ROAD_TYPES[editing.type]||'移除自建道路'} · 點選或拖曳空格（最多 24 格） · Esc 取消`;};
$('#fire-alert').onclick=()=>{const b=town.buildings.find(b=>b.fireWarningAt!==undefined)||town.buildings.find(damaged);if(!b)return;stopFollowing();setMode('explore');pinned={kind:'building',id:b.id};hovered=null;scene.focusAt([b.x*CELL,b.z*CELL],2.6);renderInspector();};
$('#public-fire').onclick=()=>{$('#public-works').close();plotSize=1;setMode('garden');selectedDesign='firePost';$('#blueprint-status').textContent='街坊巡守所 · 每格100文';$('#blueprint-status').hidden=false;$('#mode-hint').textContent='街坊巡守所 · 點蓋或斜拉四格 · 沿路覆蓋附近建築';$('#welcome').hidden=true;};
$('#public-cleaning').onclick=()=>{$('#public-works').close();plotSize=1;setMode('garden');selectedDesign='cleaningYard';$('#blueprint-status').textContent='街坊清運院 · 每格100文';$('#blueprint-status').hidden=false;$('#mode-hint').textContent='街坊清運院 · 點蓋或斜拉四格 · 須以道路接至住宅與作坊';$('#welcome').hidden=true;};
$('#public-water').onclick=()=>{$('#public-works').close();plotSize=1;setMode('garden');selectedDesign='well';$('#blueprint-status').textContent='街坊水井 · 每格100文 · 落成後供水';$('#blueprint-status').hidden=false;$('#mode-hint').textContent='街坊水井 · 點蓋一格或斜拉四格井院 · 須有步道接到住宅';$('#welcome').hidden=true;};
$('#public-garden').onclick=()=>{$('#public-works').close();plotSize=1;designFilter='garden';renderBlueprints();$('#blueprints').showModal();};
$('#demolish-confirm').onclick=()=>{const id=pendingDelete;$('#demolish').close();stopFollowing();if(applyUrban(draft=>demolishBuilding(draft,id))){pinned=hovered=null;toast('已拆除，住戶與貨物妥善保留；可復原上一步');}};
$('#undo-urban').onclick=()=>{if(!undoTown)return;$('#undo-description').textContent=`將整座小鎮回到第 ${Math.floor(undoTown.time/24)+1} 日 ${formatTime(undoTown.time)}（操作前）。這會一起回復建築、道路、居民位置與貨物；其後約 ${Math.max(0,Math.round(town.elapsed-undoTown.elapsed))} 秒的模擬進度也會回復。`;$('#confirm-undo').showModal();};
$('#undo-confirm').onclick=()=>{if(!undoTown)return;const target=undoTown;if(!applyUrban(draft=>{Object.assign(draft,Town.restore(target));return true;}))return;stopFollowing();undoTown=null;pinned=hovered=null;setMode('explore');$('#undo-urban').hidden=true;$('#welcome').hidden=!!town.buildings.length;$('#confirm-undo').close();toast('已回到確認視窗所列的操作前時間');};

$('#stalls-btn').onclick=()=>{const stalls=marketStalls(town);$('#stalls-list').innerHTML=stalls.length?stalls.map(stallListItem).join(''):'<p>先讓商鋪或說書棚落成，或將道路鋪成 2 × 2 廣場，攤販便會出現。</p>';$('#public-works').close();$('#stalls').showModal();};
$('#stalls').onclick=e=>{const b=e.target.closest('[data-stall-focus]');if(!b)return;const s=marketStalls(town).find(s=>s.id===b.dataset.stallFocus);if(!s)return;$('#stalls').close();stopFollowing();setMode('explore');pinned={kind:'stall',id:s.id};hovered=null;scene.focusAt([s.x,s.z],2.8);renderInspector();};

if(!fixtureMode)saveUI=installSaveUI({store:saveStore,getTown:()=>town.toJSON(),prepareTown:data=>Town.restore(data),pause:()=>{if(!paused)$('#pause-btn').click();},replaceTown:restored=>{stopFollowing();town=restored;runtime.reset();recovery=new RecoveryPoint({read:()=>town.toJSON(),validate:validateSave});undoTown=null;pinned=hovered=null;selectedLot=null;scene.reset();scene.resetView();setMode('explore');$('#undo-urban').hidden=true;$('#welcome').hidden=!!town.buildings.length;$('#inspector').hidden=true;toast('已讀取選定版本，小鎮暫停中');save();}});else $('#save-manager-btn').onclick=()=>toast('預覽場景不寫入存檔；請使用一般小鎮的存檔管理');

const financeUI=installFinanceUI({getTown:()=>town,edit:fn=>{const result=applyUrban(fn);if(result)setMode('explore');return result;}});
