import {LITERARY_QUESTS,LANDMARK_QUEST,questEntry,requirements} from './literary-quests.js';
import {escapeHTML as esc} from './content-html.js';
export const STAGE_ORDER=['yueyang','kaifeng','printing','zuiweng','lotus','redcliff','oil','creek','lantern','moon'];
const THEMES={yueyang:['憂','百姓安居，重修名樓'],kaifeng:['公','訪查線索，公正說理'],printing:['印','排字製版，印書傳文'],zuiweng:['亭','循山訪泉，與民同樂'],lotus:['蓮','觀物比德，營造蓮池'],redcliff:['舟','主客問答，夜航赤壁'],oil:['藝','分解工序，熟能生巧'],creek:['荷','誤入荷塘，驚起鷗鷺'],lantern:['燈','燈市尋人，詞中訪景'],moon:['月','寄信遠方，共賞明月']};
export function stageEntries(t){return STAGE_ORDER.map((id,i)=>{const q=LITERARY_QUESTS[id],e=questEntry(t,id),design=Object.keys(LANDMARK_QUEST).find(d=>LANDMARK_QUEST[d]===id),built=t.buildings.filter(b=>b.design===design&&b.stage>=3),reading=Math.min(3,e.step),activity=e.activity?.stage||0,complete=reading===3&&activity===3&&built.length>0;return {id,number:i+1,name:q.name,author:q.author,title:THEMES[id][1],seal:THEMES[id][0],reading,activity,design,built:built.length,tier:Math.max(0,...built.map(b=>b.tier||1)),complete,unlocked:e.step===4,requirements:requirements(t,id),progress:reading+activity+Number(built.length>0),steps:q.steps.map(s=>s.title)};});}
export function installStageSelect({getTown,openQuest,openAccount}){
 const dialog=document.createElement('dialog');dialog.id='stage-select';dialog.setAttribute('aria-labelledby','stage-title');document.body.append(dialog);let filter='all';
 function render(){const all=stageEntries(getTown()),rows=all.filter(s=>filter==='all'||filter==='complete'&&s.complete||filter==='unfinished'&&!s.complete);dialog.innerHTML=`<header class="stage-heading"><div><p class="stage-eyebrow">汴水小鎮 · 宋韻文學之旅</p><h2 id="stage-title">選一段故事，築一座小鎮</h2></div><button data-stage-close aria-label="關閉選關">回到小鎮</button></header><p>十段文學旅程自由選擇。每關依序完成閱讀、場景操作與地標營造；共用目前的小鎮，換關不會清除建築或進度。</p><div class="stage-summary"><strong>已通關 ${all.filter(s=>s.complete).length}／10</strong><span>通關＝閱讀 3/3＋操作 3/3＋地標落成；五級營造是進階挑戰。</span><button data-stage-account>Google 登入與雲端存檔</button></div><nav class="stage-filters" aria-label="關卡篩選">${[['all','全部關卡'],['unfinished','尚未通關'],['complete','已通關']].map(([id,name])=>`<button data-stage-filter="${id}" aria-pressed="${filter===id}">${name}</button>`).join('')}</nav><div class="stage-grid">${rows.map(s=>`<article class="stage-card stage-${s.id}"><div class="stage-card-top"><span>第 ${String(s.number).padStart(2,'0')} 關</span><span>${s.complete?'✓ 已通關':s.unlocked?'圖樣已解鎖':s.progress?'進行中':'可開始'}</span></div><div class="stage-scene" aria-hidden="true"><span>${s.seal}</span><i></i></div><h3>${esc(s.name)}</h3><p class="stage-author">${esc(s.author)}</p><p>${esc(s.title)}</p><progress max="7" value="${s.progress}" aria-label="${esc(s.name)}進度 ${s.progress}／7"></progress><p class="stage-progress">閱讀 ${s.reading}/3 · 操作 ${s.activity}/3 · 地標 ${s.built?'已落成':'待營造'}${s.tier?` · ${s.tier}級`:''}</p><details><summary>這關要完成什麼？</summary><ol>${s.steps.map(x=>`<li>${esc(x)}</li>`).join('')}<li>完成三個場景操作，解鎖並營造四格地標</li></ol><p>城鎮準備：${s.requirements.map(r=>`${r.ok?'✓':'○'} ${esc(r.name)}`).join('、')}</p>${s.id==='yueyang'?'<p>岳陽樓須臨東側河岸或緊鄰已落成池塘／文學水景。</p>':''}</details><button class="stage-enter" data-stage-enter="${s.id}">${s.complete?'重訪本關':s.progress?'繼續本關':'開始本關'} →</button></article>`).join('')||'<p>目前沒有符合的關卡。</p>'}</div><footer><button data-stage-close>繼續自由營造</button><span>不登入也能遊玩；本機進度仍會保留。</span></footer>`;}
 const open=()=>{render();if(!dialog.open)dialog.showModal();};dialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-stage-close'))dialog.close();else if(b.dataset.stageFilter){filter=b.dataset.stageFilter;render();}else if(b.dataset.stageEnter){dialog.close();openQuest(b.dataset.stageEnter);}else if(b.hasAttribute('data-stage-account')){dialog.close();openAccount();}};
 document.querySelector('#stage-select-btn').onclick=open;return {open};
}
